<?php

namespace Database\Seeders;

use App\Models\AffiliateLink;
use Illuminate\Database\Seeder;

/**
 * Seeder pour les liens affiliés - Couverture mondiale 197 pays
 * 
 * Structure :
 * - GLOBAL : Disponibles dans tous les pays
 * - RÉGIONAL : Disponibles par région (europe, asia, africa, middle_east, north_america, latin_america, oceania)
 * - PAYS : Disponibles dans des pays spécifiques
 * 
 * Catégories :
 * - transfer : Transferts d'argent
 * - insurance : Assurances santé
 * - housing : Hébergement
 * - moving : Déménagement
 * - bank : Banques
 * - language : Apprentissage langues
 * - vpn : VPN & Sécurité
 * - telecom : Télécom & SIM
 * - community : Communauté expatriés
 * - legal : Services juridiques
 * - job : Emploi international
 */
class AffiliateLinkSeeder extends Seeder
{
    public function run(): void
    {
        $affiliates = array_merge(
            $this->getGlobalAffiliates(),
            $this->getEuropeAffiliates(),
            $this->getAsiaAffiliates(),
            $this->getAfricaAffiliates(),
            $this->getMiddleEastAffiliates(),
            $this->getNorthAmericaAffiliates(),
            $this->getLatinAmericaAffiliates(),
            $this->getOceaniaAffiliates()
        );

        foreach ($affiliates as $affiliate) {
            AffiliateLink::create($affiliate);
        }

        $this->command->info('   ✅ ' . count($affiliates) . ' liens affiliés créés (couverture mondiale)');
    }

    /**
     * ═══════════════════════════════════════════════════════════════════════════
     * PARTENAIRES GLOBAUX - Disponibles dans 197 pays
     * ═══════════════════════════════════════════════════════════════════════════
     */
    private function getGlobalAffiliates(): array
    {
        return [
            // ─────────────────────────────────────────────────────────────────────
            // TRANSFERTS D'ARGENT - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'Wise (TransferWise)',
                'slug' => 'wise',
                'category' => 'transfer',
                'url' => 'https://wise.com/invite/u/[AFFILIATE_ID]',
                'anchor_text' => 'Wise - International transfers at real exchange rate',
                'description' => 'Send money abroad with the real exchange rate. Available in 170+ countries.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'], // Pays sanctionnés
                'keywords' => ['transfer money', 'send money', 'exchange rate', 'wire transfer', 'international transfer', 'remittance', 'envoi argent', 'virement international', 'transfert', 'cambio', 'überweisen', 'перевод денег', '汇款', 'تحويل أموال', 'पैसे भेजें'],
                'commission_type' => 'cpa',
                'commission_rate' => 15.00,
                'commission_currency' => 'GBP',
                'cookie_duration_days' => 30,
                'priority' => 100,
                'is_active' => true,
            ],
            [
                'name' => 'Western Union',
                'slug' => 'western-union',
                'category' => 'transfer',
                'url' => 'https://www.westernunion.com/[AFFILIATE_ID]',
                'anchor_text' => 'Western Union - Send money worldwide',
                'description' => 'Send money to 200+ countries. Cash pickup or bank transfer.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['KP'],
                'keywords' => ['western union', 'cash pickup', 'send money', 'money transfer', 'retrait espèces', 'envoi argent', 'geldtransfer', 'денежный перевод', '西联汇款', 'ويسترن يونيون', 'वेस्टर्न यूनियन'],
                'commission_type' => 'percentage',
                'commission_rate' => 3.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'WorldRemit',
                'slug' => 'worldremit',
                'category' => 'transfer',
                'url' => 'https://www.worldremit.com/[AFFILIATE_ID]',
                'anchor_text' => 'WorldRemit - Fast money transfers',
                'description' => 'Send money online to 130+ countries. Mobile money, bank transfer, cash pickup.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'],
                'keywords' => ['worldremit', 'mobile money', 'send money', 'fast transfer', 'money transfer', 'transfert rapide', 'dinero móvil'],
                'commission_type' => 'cpa',
                'commission_rate' => 10.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'Remitly',
                'slug' => 'remitly',
                'category' => 'transfer',
                'url' => 'https://www.remitly.com/[AFFILIATE_ID]',
                'anchor_text' => 'Remitly - Send money to family',
                'description' => 'Fast, secure money transfers to 100+ countries.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'],
                'keywords' => ['remitly', 'family transfer', 'send money family', 'envoi famille', 'remittance', 'enviar dinero familia', 'Geld an Familie senden'],
                'commission_type' => 'cpa',
                'commission_rate' => 10.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'PayPal',
                'slug' => 'paypal',
                'category' => 'transfer',
                'url' => 'https://www.paypal.com/[AFFILIATE_ID]',
                'anchor_text' => 'PayPal - Secure online payments',
                'description' => 'Send and receive money online. Available in 200+ countries.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY', 'RU'],
                'keywords' => ['paypal', 'online payment', 'send money online', 'paiement en ligne', 'pago en línea', 'pagamento online'],
                'commission_type' => 'cpa',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'Payoneer',
                'slug' => 'payoneer',
                'category' => 'transfer',
                'url' => 'https://www.payoneer.com/[AFFILIATE_ID]',
                'anchor_text' => 'Payoneer - Global payment platform',
                'description' => 'Receive payments from international clients. Multi-currency account.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'],
                'keywords' => ['payoneer', 'freelancer payment', 'receive payment', 'international payment', 'paiement freelance', 'multi-currency'],
                'commission_type' => 'cpa',
                'commission_rate' => 25.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],

            // ─────────────────────────────────────────────────────────────────────
            // ASSURANCES SANTÉ - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'Cigna Global',
                'slug' => 'cigna-global',
                'category' => 'insurance',
                'url' => 'https://www.cignaglobal.com/[AFFILIATE_ID]',
                'anchor_text' => 'Cigna Global - International health insurance',
                'description' => 'Comprehensive health coverage for expats worldwide.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'],
                'keywords' => ['health insurance', 'expat insurance', 'international insurance', 'medical coverage', 'assurance santé', 'seguro médico', 'krankenversicherung', 'медицинская страховка', '健康保险', 'تأمين صحي', 'स्वास्थ्य बीमा'],
                'commission_type' => 'percentage',
                'commission_rate' => 7.50,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 95,
                'is_active' => true,
            ],
            [
                'name' => 'Allianz Care',
                'slug' => 'allianz-care',
                'category' => 'insurance',
                'url' => 'https://www.allianzcare.com/[AFFILIATE_ID]',
                'anchor_text' => 'Allianz Care - Global health protection',
                'description' => 'Health insurance solutions for expats and international companies.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'],
                'keywords' => ['allianz', 'health insurance', 'expat health', 'global coverage', 'assurance expatrié', 'seguro expatriado'],
                'commission_type' => 'percentage',
                'commission_rate' => 7.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 60,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'AXA Global Healthcare',
                'slug' => 'axa-global',
                'category' => 'insurance',
                'url' => 'https://www.axaglobalhealthcare.com/[AFFILIATE_ID]',
                'anchor_text' => 'AXA - International health insurance',
                'description' => 'Premium health insurance for individuals and families abroad.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'],
                'keywords' => ['axa', 'premium insurance', 'family health', 'international coverage', 'assurance famille'],
                'commission_type' => 'percentage',
                'commission_rate' => 6.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 60,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'SafetyWing',
                'slug' => 'safetywing',
                'category' => 'insurance',
                'url' => 'https://safetywing.com/[AFFILIATE_ID]',
                'anchor_text' => 'SafetyWing - Insurance for nomads',
                'description' => 'Affordable travel and health insurance for digital nomads and remote workers.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'],
                'keywords' => ['digital nomad', 'nomad insurance', 'travel insurance', 'remote worker', 'assurance nomade', 'seguro nómada', 'working abroad'],
                'commission_type' => 'percentage',
                'commission_rate' => 10.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],

            // ─────────────────────────────────────────────────────────────────────
            // HÉBERGEMENT - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'Booking.com',
                'slug' => 'booking',
                'category' => 'housing',
                'url' => 'https://www.booking.com/[AFFILIATE_ID]',
                'anchor_text' => 'Booking.com - Hotels & accommodations worldwide',
                'description' => 'Book hotels, apartments and accommodations in 220+ countries.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['hotel', 'accommodation', 'booking', 'lodging', 'hôtel', 'hébergement', 'alojamiento', 'unterkunft', 'гостиница', '酒店', 'فندق', 'होटल'],
                'commission_type' => 'percentage',
                'commission_rate' => 4.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 95,
                'is_active' => true,
            ],
            [
                'name' => 'Airbnb',
                'slug' => 'airbnb',
                'category' => 'housing',
                'url' => 'https://www.airbnb.com/c/[AFFILIATE_ID]',
                'anchor_text' => 'Airbnb - Unique stays worldwide',
                'description' => 'Find temporary housing during your relocation.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CU', 'IR', 'KP', 'SY'],
                'keywords' => ['airbnb', 'apartment', 'vacation rental', 'temporary housing', 'appartement', 'location', 'alquiler', 'wohnung', 'квартира', '公寓', 'شقة', 'अपार्टमेंट'],
                'commission_type' => 'percentage',
                'commission_rate' => 3.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'Agoda',
                'slug' => 'agoda',
                'category' => 'housing',
                'url' => 'https://www.agoda.com/[AFFILIATE_ID]',
                'anchor_text' => 'Agoda - Best hotel deals',
                'description' => 'Book hotels at the best prices. Strong coverage in Asia.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['agoda', 'hotel deals', 'cheap hotel', 'best price', 'hotel pas cher', 'hotel barato', 'günstiges hotel'],
                'commission_type' => 'percentage',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'HousingAnywhere',
                'slug' => 'housinganywhere',
                'category' => 'housing',
                'url' => 'https://housinganywhere.com/[AFFILIATE_ID]',
                'anchor_text' => 'HousingAnywhere - Mid-term rentals',
                'description' => 'Find furnished apartments for 1-12 months. Perfect for expats.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['mid-term rental', 'furnished apartment', 'expat housing', 'relocation housing', 'location meublée', 'appartement meublé'],
                'commission_type' => 'cpa',
                'commission_rate' => 50.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],

            // ─────────────────────────────────────────────────────────────────────
            // VPN & SÉCURITÉ - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'NordVPN',
                'slug' => 'nordvpn',
                'category' => 'vpn',
                'url' => 'https://nordvpn.com/[AFFILIATE_ID]',
                'anchor_text' => 'NordVPN - Secure your connection',
                'description' => 'Access your favorite content from anywhere. Top security.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['vpn', 'security', 'streaming', 'secure connection', 'privacy', 'connexion sécurisée', 'sécurité', 'seguridad', 'sicherheit', 'безопасность', '安全', 'أمان', 'सुरक्षा'],
                'commission_type' => 'percentage',
                'commission_rate' => 40.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 95,
                'is_active' => true,
            ],
            [
                'name' => 'ExpressVPN',
                'slug' => 'expressvpn',
                'category' => 'vpn',
                'url' => 'https://www.expressvpn.com/[AFFILIATE_ID]',
                'anchor_text' => 'ExpressVPN - Fast & secure VPN',
                'description' => 'Premium VPN for expats. Access content from anywhere.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['expressvpn', 'fast vpn', 'streaming vpn', 'netflix vpn', 'vpn rapide', 'vpn rápido'],
                'commission_type' => 'percentage',
                'commission_rate' => 35.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'Surfshark',
                'slug' => 'surfshark',
                'category' => 'vpn',
                'url' => 'https://surfshark.com/[AFFILIATE_ID]',
                'anchor_text' => 'Surfshark - Affordable VPN',
                'description' => 'Unlimited devices, great price. Perfect for families.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['surfshark', 'cheap vpn', 'family vpn', 'unlimited vpn', 'vpn pas cher', 'vpn económico'],
                'commission_type' => 'percentage',
                'commission_rate' => 40.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],

            // ─────────────────────────────────────────────────────────────────────
            // LANGUES - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'Preply',
                'slug' => 'preply',
                'category' => 'language',
                'url' => 'https://preply.com/[AFFILIATE_ID]',
                'anchor_text' => 'Preply - Online language tutors',
                'description' => 'Find a private language tutor for online lessons.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['language tutor', 'online lessons', 'private teacher', 'learn language', 'professeur particulier', 'cours en ligne', 'profesor particular', 'sprachlehrer', 'репетитор', '语言老师', 'مدرس لغة', 'भाषा शिक्षक'],
                'commission_type' => 'cpa',
                'commission_rate' => 15.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'italki',
                'slug' => 'italki',
                'category' => 'language',
                'url' => 'https://www.italki.com/[AFFILIATE_ID]',
                'anchor_text' => 'italki - Native language teachers',
                'description' => 'Learn with native speakers from around the world.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['italki', 'native speaker', 'conversation practice', 'language exchange', 'locuteur natif', 'hablante nativo', 'muttersprachler'],
                'commission_type' => 'cpa',
                'commission_rate' => 10.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'Babbel',
                'slug' => 'babbel',
                'category' => 'language',
                'url' => 'https://www.babbel.com/[AFFILIATE_ID]',
                'anchor_text' => 'Babbel - Learn a new language',
                'description' => 'Language learning app with proven methodology.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['babbel', 'learn language', 'language app', 'apprendre langue', 'aprender idioma', 'sprache lernen'],
                'commission_type' => 'percentage',
                'commission_rate' => 20.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],

            // ─────────────────────────────────────────────────────────────────────
            // COMMUNAUTÉ - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'InterNations',
                'slug' => 'internations',
                'category' => 'community',
                'url' => 'https://www.internations.org/[AFFILIATE_ID]',
                'anchor_text' => 'InterNations - Global expat community',
                'description' => 'Join the largest expat community. Events, networking, friends.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['expat community', 'networking', 'expat events', 'meet expats', 'communauté expatriés', 'comunidad expatriados', 'expat-gemeinschaft', 'сообщество экспатов', '外籍人士社区', 'مجتمع المغتربين', 'प्रवासी समुदाय'],
                'commission_type' => 'cpa',
                'commission_rate' => 25.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],

            // ─────────────────────────────────────────────────────────────────────
            // DÉMÉNAGEMENT - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'International Van Lines',
                'slug' => 'international-van-lines',
                'category' => 'moving',
                'url' => 'https://www.internationalvanlines.com/[AFFILIATE_ID]',
                'anchor_text' => 'International Van Lines - Global moving',
                'description' => 'International moving services to 180+ countries.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['international moving', 'relocation', 'moving abroad', 'déménagement international', 'mudanza internacional', 'internationale umzüge', 'международный переезд', '国际搬家'],
                'commission_type' => 'cpl',
                'commission_rate' => 50.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 80,
                'is_active' => true,
            ],

            // ─────────────────────────────────────────────────────────────────────
            // TÉLÉCOM - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'Airalo',
                'slug' => 'airalo',
                'category' => 'telecom',
                'url' => 'https://www.airalo.com/[AFFILIATE_ID]',
                'anchor_text' => 'Airalo - eSIM for travelers',
                'description' => 'Buy eSIM online for 200+ countries. Stay connected anywhere.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['esim', 'travel sim', 'international sim', 'roaming', 'sim card', 'carte sim', 'tarjeta sim', 'sim-karte', 'сим-карта', 'SIM卡', 'بطاقة SIM', 'सिम कार्ड'],
                'commission_type' => 'percentage',
                'commission_rate' => 15.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'Holafly',
                'slug' => 'holafly',
                'category' => 'telecom',
                'url' => 'https://www.holafly.com/[AFFILIATE_ID]',
                'anchor_text' => 'Holafly - Unlimited data eSIM',
                'description' => 'eSIM with unlimited data in 160+ destinations.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['holafly', 'unlimited data', 'esim unlimited', 'data abroad', 'internet abroad', 'données illimitées', 'datos ilimitados'],
                'commission_type' => 'percentage',
                'commission_rate' => 12.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],

            // ─────────────────────────────────────────────────────────────────────
            // EMPLOI - GLOBAL
            // ─────────────────────────────────────────────────────────────────────
            [
                'name' => 'LinkedIn Premium',
                'slug' => 'linkedin-premium',
                'category' => 'job',
                'url' => 'https://www.linkedin.com/premium/[AFFILIATE_ID]',
                'anchor_text' => 'LinkedIn Premium - Find jobs abroad',
                'description' => 'Access premium job search features and InMail.',
                'is_global' => true,
                'regions' => null,
                'countries' => null,
                'excluded_countries' => ['CN', 'RU'],
                'keywords' => ['linkedin', 'job search', 'career', 'professional network', 'recherche emploi', 'buscar empleo', 'jobsuche', 'поиск работы', 'नौकरी खोज'],
                'commission_type' => 'cpa',
                'commission_rate' => 20.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
        ];
    }

    /**
     * ═══════════════════════════════════════════════════════════════════════════
     * PARTENAIRES EUROPE
     * ═══════════════════════════════════════════════════════════════════════════
     */
    private function getEuropeAffiliates(): array
    {
        return [
            // BANQUES - EUROPE
            [
                'name' => 'N26',
                'slug' => 'n26',
                'category' => 'bank',
                'url' => 'https://n26.com/r/[AFFILIATE_ID]',
                'anchor_text' => 'N26 - Mobile bank for Europe',
                'description' => 'European mobile bank. Free account, no paperwork.',
                'is_global' => false,
                'regions' => ['europe'],
                'countries' => null,
                'excluded_countries' => ['RU', 'BY'],
                'keywords' => ['n26', 'mobile bank', 'european bank', 'digital bank', 'banque mobile', 'banco móvil', 'mobile banking'],
                'commission_type' => 'cpa',
                'commission_rate' => 15.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'Revolut',
                'slug' => 'revolut',
                'category' => 'bank',
                'url' => 'https://revolut.com/referral/[AFFILIATE_ID]',
                'anchor_text' => 'Revolut - Multi-currency account',
                'description' => 'Multi-currency account with interbank exchange rate.',
                'is_global' => false,
                'regions' => ['europe'],
                'countries' => ['US', 'AU', 'SG', 'JP'],
                'excluded_countries' => null,
                'keywords' => ['revolut', 'multi-currency', 'exchange rate', 'card abroad', 'compte multi-devises', 'cuenta multidivisa'],
                'commission_type' => 'cpa',
                'commission_rate' => 10.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'Monzo',
                'slug' => 'monzo',
                'category' => 'bank',
                'url' => 'https://monzo.com/[AFFILIATE_ID]',
                'anchor_text' => 'Monzo - Smart UK banking',
                'description' => 'UK digital bank with smart features.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['GB'],
                'excluded_countries' => null,
                'keywords' => ['monzo', 'uk bank', 'british bank', 'smart bank'],
                'commission_type' => 'cpa',
                'commission_rate' => 5.00,
                'commission_currency' => 'GBP',
                'cookie_duration_days' => 30,
                'priority' => 70,
                'is_active' => true,
            ],

            // ASSURANCES - EUROPE
            [
                'name' => 'April International',
                'slug' => 'april-international',
                'category' => 'insurance',
                'url' => 'https://www.april-international.com/[AFFILIATE_ID]',
                'anchor_text' => 'April International - Assurance expatriés',
                'description' => 'Assurance santé internationale pour expatriés francophones.',
                'is_global' => false,
                'regions' => ['europe'],
                'countries' => ['MA', 'TN', 'SN', 'CI', 'MG', 'MU'],
                'excluded_countries' => null,
                'keywords' => ['april', 'assurance expatrié', 'cfe', 'assurance française', 'mutuelle expatrié', 'french insurance'],
                'commission_type' => 'percentage',
                'commission_rate' => 8.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 60,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'MSH International',
                'slug' => 'msh-international',
                'category' => 'insurance',
                'url' => 'https://www.msh-intl.com/[AFFILIATE_ID]',
                'anchor_text' => 'MSH International - Global health coverage',
                'description' => 'International health insurance for expats and companies.',
                'is_global' => false,
                'regions' => ['europe'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['msh', 'corporate insurance', 'group insurance', 'assurance entreprise'],
                'commission_type' => 'percentage',
                'commission_rate' => 6.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 60,
                'priority' => 75,
                'is_active' => true,
            ],

            // DÉMÉNAGEMENT - EUROPE
            [
                'name' => 'AGS Déménagement',
                'slug' => 'ags-demenagement',
                'category' => 'moving',
                'url' => 'https://www.ags-globalsolutions.com/[AFFILIATE_ID]',
                'anchor_text' => 'AGS - International moving experts',
                'description' => 'Leader in international moving for individuals and companies.',
                'is_global' => false,
                'regions' => ['europe', 'africa'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['ags', 'déménagement', 'international moving', 'relocation europe', 'mudanza europa'],
                'commission_type' => 'cpl',
                'commission_rate' => 40.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 60,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Sirelo',
                'slug' => 'sirelo',
                'category' => 'moving',
                'url' => 'https://www.sirelo.com/[AFFILIATE_ID]',
                'anchor_text' => 'Sirelo - Compare moving quotes',
                'description' => 'Compare international moving quotes from certified movers.',
                'is_global' => false,
                'regions' => ['europe'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['sirelo', 'moving quotes', 'compare movers', 'devis déménagement', 'comparateur déménagement'],
                'commission_type' => 'cpl',
                'commission_rate' => 30.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 75,
                'is_active' => true,
            ],

            // LOGEMENT - EUROPE
            [
                'name' => 'Spotahome',
                'slug' => 'spotahome',
                'category' => 'housing',
                'url' => 'https://www.spotahome.com/[AFFILIATE_ID]',
                'anchor_text' => 'Spotahome - Mid-term rentals in Europe',
                'description' => 'Verified apartments for medium-term stays in European cities.',
                'is_global' => false,
                'regions' => ['europe'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['spotahome', 'long term rental', 'apartment europe', 'location longue durée', 'alquiler largo plazo'],
                'commission_type' => 'cpa',
                'commission_rate' => 50.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],
        ];
    }

    /**
     * ═══════════════════════════════════════════════════════════════════════════
     * PARTENAIRES ASIE
     * ═══════════════════════════════════════════════════════════════════════════
     */
    private function getAsiaAffiliates(): array
    {
        return [
            // BANQUES - ASIE
            [
                'name' => 'HSBC Expat',
                'slug' => 'hsbc-expat',
                'category' => 'bank',
                'url' => 'https://www.expat.hsbc.com/[AFFILIATE_ID]',
                'anchor_text' => 'HSBC Expat - International banking',
                'description' => 'Offshore banking for expats. Manage money across borders.',
                'is_global' => false,
                'regions' => ['asia', 'middle_east', 'europe'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['hsbc', 'offshore bank', 'expat banking', 'international bank', 'banque offshore', 'banco internacional'],
                'commission_type' => 'cpa',
                'commission_rate' => 100.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'DBS Bank',
                'slug' => 'dbs-bank',
                'category' => 'bank',
                'url' => 'https://www.dbs.com/[AFFILIATE_ID]',
                'anchor_text' => 'DBS - Leading Asian bank',
                'description' => 'Asia\'s safest bank. Digital banking excellence.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['SG', 'HK', 'TW', 'ID', 'IN', 'CN'],
                'excluded_countries' => null,
                'keywords' => ['dbs', 'singapore bank', 'asian bank', 'digital banking asia', '新加坡银行'],
                'commission_type' => 'cpa',
                'commission_rate' => 50.00,
                'commission_currency' => 'SGD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Bangkok Bank',
                'slug' => 'bangkok-bank',
                'category' => 'bank',
                'url' => 'https://www.bangkokbank.com/[AFFILIATE_ID]',
                'anchor_text' => 'Bangkok Bank - Thailand banking',
                'description' => 'Leading Thai bank with expat-friendly services.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['TH'],
                'excluded_countries' => null,
                'keywords' => ['bangkok bank', 'thai bank', 'thailand banking', 'banque thaïlande', 'ธนาคารกรุงเทพ'],
                'commission_type' => 'cpl',
                'commission_rate' => 20.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 70,
                'is_active' => true,
            ],

            // ASSURANCES - ASIE
            [
                'name' => 'Pacific Prime',
                'slug' => 'pacific-prime',
                'category' => 'insurance',
                'url' => 'https://www.pacificprime.com/[AFFILIATE_ID]',
                'anchor_text' => 'Pacific Prime - Asia health insurance',
                'description' => 'Health insurance broker specializing in Asia-Pacific.',
                'is_global' => false,
                'regions' => ['asia', 'oceania'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['pacific prime', 'asia insurance', 'hong kong insurance', 'singapore insurance', 'assurance asie', '亚洲保险'],
                'commission_type' => 'percentage',
                'commission_rate' => 8.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'AIA',
                'slug' => 'aia',
                'category' => 'insurance',
                'url' => 'https://www.aia.com/[AFFILIATE_ID]',
                'anchor_text' => 'AIA - Asia\'s largest insurer',
                'description' => 'Leading life and health insurance in Asia-Pacific.',
                'is_global' => false,
                'regions' => ['asia', 'oceania'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['aia', 'asia insurance', 'life insurance asia', 'health insurance asia', '友邦保险'],
                'commission_type' => 'percentage',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 80,
                'is_active' => true,
            ],

            // TÉLÉCOM - ASIE
            [
                'name' => 'AIS (Thailand)',
                'slug' => 'ais-thailand',
                'category' => 'telecom',
                'url' => 'https://www.ais.th/[AFFILIATE_ID]',
                'anchor_text' => 'AIS - Best network in Thailand',
                'description' => 'Thailand\'s leading mobile network. Tourist and expat SIMs.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['TH'],
                'excluded_countries' => null,
                'keywords' => ['ais', 'thailand sim', 'thai mobile', 'sim thailande', 'ซิมการ์ดไทย'],
                'commission_type' => 'cpa',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 75,
                'is_active' => true,
            ],
            [
                'name' => 'Singtel',
                'slug' => 'singtel',
                'category' => 'telecom',
                'url' => 'https://www.singtel.com/[AFFILIATE_ID]',
                'anchor_text' => 'Singtel - Singapore\'s #1 network',
                'description' => 'Singapore\'s leading telecommunications provider.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['SG'],
                'excluded_countries' => null,
                'keywords' => ['singtel', 'singapore mobile', 'singapore sim', 'sim singapour', '新加坡电信'],
                'commission_type' => 'cpa',
                'commission_rate' => 10.00,
                'commission_currency' => 'SGD',
                'cookie_duration_days' => 30,
                'priority' => 75,
                'is_active' => true,
            ],

            // SERVICES - ASIE
            [
                'name' => 'Grab',
                'slug' => 'grab',
                'category' => 'transfer',
                'url' => 'https://www.grab.com/[AFFILIATE_ID]',
                'anchor_text' => 'Grab - Ride, food & payments',
                'description' => 'Southeast Asia\'s super app. Transport, food, payments.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['SG', 'MY', 'TH', 'VN', 'ID', 'PH', 'MM', 'KH'],
                'excluded_countries' => null,
                'keywords' => ['grab', 'taxi asia', 'food delivery asia', 'grabpay', 'transport asie'],
                'commission_type' => 'cpa',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
        ];
    }

    /**
     * ═══════════════════════════════════════════════════════════════════════════
     * PARTENAIRES AFRIQUE
     * ═══════════════════════════════════════════════════════════════════════════
     */
    private function getAfricaAffiliates(): array
    {
        return [
            // MOBILE MONEY - AFRIQUE
            [
                'name' => 'M-Pesa',
                'slug' => 'm-pesa',
                'category' => 'transfer',
                'url' => 'https://www.safaricom.co.ke/m-pesa/[AFFILIATE_ID]',
                'anchor_text' => 'M-Pesa - Mobile money Africa',
                'description' => 'Africa\'s leading mobile money service. Send and receive instantly.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['KE', 'TZ', 'UG', 'RW', 'CD', 'MZ', 'GH', 'EG'],
                'excluded_countries' => null,
                'keywords' => ['m-pesa', 'mpesa', 'mobile money', 'kenya money', 'africa transfer', 'argent mobile afrique', 'transfert afrique'],
                'commission_type' => 'percentage',
                'commission_rate' => 2.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'Orange Money',
                'slug' => 'orange-money',
                'category' => 'transfer',
                'url' => 'https://www.orange.com/money/[AFFILIATE_ID]',
                'anchor_text' => 'Orange Money - Mobile payments',
                'description' => 'Mobile money for francophone Africa. Pay, send, receive.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['SN', 'CI', 'ML', 'BF', 'CM', 'MG', 'MA', 'TN'],
                'excluded_countries' => null,
                'keywords' => ['orange money', 'mobile money', 'argent mobile', 'paiement mobile', 'transfert afrique', 'africa payment'],
                'commission_type' => 'percentage',
                'commission_rate' => 2.00,
                'commission_currency' => 'EUR',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'MTN Mobile Money',
                'slug' => 'mtn-momo',
                'category' => 'transfer',
                'url' => 'https://www.mtn.com/momo/[AFFILIATE_ID]',
                'anchor_text' => 'MTN MoMo - Mobile money',
                'description' => 'MTN Mobile Money across Africa. Fast, secure transfers.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['GH', 'UG', 'RW', 'ZM', 'CM', 'BJ', 'CI', 'CG'],
                'excluded_countries' => null,
                'keywords' => ['mtn', 'momo', 'mobile money', 'ghana money', 'uganda money', 'africa mobile'],
                'commission_type' => 'percentage',
                'commission_rate' => 2.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Chipper Cash',
                'slug' => 'chipper-cash',
                'category' => 'transfer',
                'url' => 'https://chippercash.com/[AFFILIATE_ID]',
                'anchor_text' => 'Chipper Cash - Free transfers in Africa',
                'description' => 'No-fee cross-border payments in Africa.',
                'is_global' => false,
                'regions' => ['africa'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['chipper', 'africa transfer', 'free transfer africa', 'transfert gratuit afrique', 'paiement afrique'],
                'commission_type' => 'cpa',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],

            // BANQUES - AFRIQUE
            [
                'name' => 'Ecobank',
                'slug' => 'ecobank',
                'category' => 'bank',
                'url' => 'https://www.ecobank.com/[AFFILIATE_ID]',
                'anchor_text' => 'Ecobank - Pan-African banking',
                'description' => 'Banking across 33 African countries.',
                'is_global' => false,
                'regions' => ['africa'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['ecobank', 'africa bank', 'pan-african', 'banque afrique', 'banco africa'],
                'commission_type' => 'cpl',
                'commission_rate' => 20.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 75,
                'is_active' => true,
            ],
            [
                'name' => 'Standard Bank',
                'slug' => 'standard-bank',
                'category' => 'bank',
                'url' => 'https://www.standardbank.com/[AFFILIATE_ID]',
                'anchor_text' => 'Standard Bank - Africa\'s largest bank',
                'description' => 'Banking and financial services across Africa.',
                'is_global' => false,
                'regions' => ['africa'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['standard bank', 'south africa bank', 'africa banking', 'banque afrique sud'],
                'commission_type' => 'cpl',
                'commission_rate' => 25.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],

            // ASSURANCES - AFRIQUE
            [
                'name' => 'Jubilee Insurance',
                'slug' => 'jubilee-insurance',
                'category' => 'insurance',
                'url' => 'https://www.jubileeinsurance.com/[AFFILIATE_ID]',
                'anchor_text' => 'Jubilee - East Africa insurance',
                'description' => 'Leading insurer in East Africa.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['KE', 'TZ', 'UG', 'RW', 'BI'],
                'excluded_countries' => null,
                'keywords' => ['jubilee', 'kenya insurance', 'east africa insurance', 'assurance kenya', 'assurance afrique est'],
                'commission_type' => 'percentage',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 75,
                'is_active' => true,
            ],
        ];
    }

    /**
     * ═══════════════════════════════════════════════════════════════════════════
     * PARTENAIRES MOYEN-ORIENT
     * ═══════════════════════════════════════════════════════════════════════════
     */
    private function getMiddleEastAffiliates(): array
    {
        return [
            // BANQUES - MOYEN-ORIENT
            [
                'name' => 'Emirates NBD',
                'slug' => 'emirates-nbd',
                'category' => 'bank',
                'url' => 'https://www.emiratesnbd.com/[AFFILIATE_ID]',
                'anchor_text' => 'Emirates NBD - UAE banking',
                'description' => 'Leading bank in the UAE and Middle East.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['AE', 'SA', 'EG'],
                'excluded_countries' => null,
                'keywords' => ['emirates nbd', 'uae bank', 'dubai bank', 'banque dubai', 'بنك الإمارات', 'банк дубай'],
                'commission_type' => 'cpl',
                'commission_rate' => 50.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'Mashreq Bank',
                'slug' => 'mashreq',
                'category' => 'bank',
                'url' => 'https://www.mashreqbank.com/[AFFILIATE_ID]',
                'anchor_text' => 'Mashreq - Digital banking UAE',
                'description' => 'Modern digital banking in the UAE.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['AE', 'BH', 'QA', 'KW'],
                'excluded_countries' => null,
                'keywords' => ['mashreq', 'uae digital bank', 'gulf bank', 'banque golfe', 'مصرف المشرق'],
                'commission_type' => 'cpl',
                'commission_rate' => 40.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],

            // ASSURANCES - MOYEN-ORIENT
            [
                'name' => 'Daman Health',
                'slug' => 'daman',
                'category' => 'insurance',
                'url' => 'https://www.damanhealth.ae/[AFFILIATE_ID]',
                'anchor_text' => 'Daman - UAE health insurance',
                'description' => 'Leading health insurer in the UAE.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['AE'],
                'excluded_countries' => null,
                'keywords' => ['daman', 'uae health insurance', 'abu dhabi insurance', 'assurance santé dubai', 'تأمين صحي الإمارات'],
                'commission_type' => 'percentage',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Bupa Arabia',
                'slug' => 'bupa-arabia',
                'category' => 'insurance',
                'url' => 'https://www.bupa.com.sa/[AFFILIATE_ID]',
                'anchor_text' => 'Bupa Arabia - Saudi health insurance',
                'description' => 'Leading health insurer in Saudi Arabia.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['SA'],
                'excluded_countries' => null,
                'keywords' => ['bupa arabia', 'saudi insurance', 'ksa health', 'assurance arabie saoudite', 'تأمين السعودية'],
                'commission_type' => 'percentage',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 80,
                'is_active' => true,
            ],

            // TÉLÉCOM - MOYEN-ORIENT
            [
                'name' => 'Etisalat',
                'slug' => 'etisalat',
                'category' => 'telecom',
                'url' => 'https://www.etisalat.ae/[AFFILIATE_ID]',
                'anchor_text' => 'Etisalat - UAE telecom',
                'description' => 'Leading telecom provider in the UAE.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['AE', 'EG', 'SA'],
                'excluded_countries' => null,
                'keywords' => ['etisalat', 'uae sim', 'dubai mobile', 'sim dubai', 'اتصالات'],
                'commission_type' => 'cpa',
                'commission_rate' => 10.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],
        ];
    }

    /**
     * ═══════════════════════════════════════════════════════════════════════════
     * PARTENAIRES AMÉRIQUE DU NORD
     * ═══════════════════════════════════════════════════════════════════════════
     */
    private function getNorthAmericaAffiliates(): array
    {
        return [
            // BANQUES - AMÉRIQUE DU NORD
            [
                'name' => 'Charles Schwab',
                'slug' => 'charles-schwab',
                'category' => 'bank',
                'url' => 'https://www.schwab.com/[AFFILIATE_ID]',
                'anchor_text' => 'Schwab - No foreign ATM fees',
                'description' => 'US bank account with no foreign transaction fees.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['US'],
                'excluded_countries' => null,
                'keywords' => ['schwab', 'us bank abroad', 'no atm fees', 'american bank expat', 'banque américaine'],
                'commission_type' => 'cpa',
                'commission_rate' => 100.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],

            // ASSURANCES - AMÉRIQUE DU NORD
            [
                'name' => 'GeoBlue',
                'slug' => 'geoblue',
                'category' => 'insurance',
                'url' => 'https://www.geobluetravelinsurance.com/[AFFILIATE_ID]',
                'anchor_text' => 'GeoBlue - US expat insurance',
                'description' => 'International health insurance for Americans abroad.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['US'],
                'excluded_countries' => null,
                'keywords' => ['geoblue', 'american expat insurance', 'us insurance abroad', 'assurance américain'],
                'commission_type' => 'percentage',
                'commission_rate' => 8.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'IMG Global',
                'slug' => 'img-global',
                'category' => 'insurance',
                'url' => 'https://www.imglobal.com/[AFFILIATE_ID]',
                'anchor_text' => 'IMG - International medical insurance',
                'description' => 'Health insurance for US citizens living abroad.',
                'is_global' => false,
                'regions' => ['north_america'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['img', 'us expat health', 'american abroad insurance', 'medical insurance abroad'],
                'commission_type' => 'percentage',
                'commission_rate' => 7.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 80,
                'is_active' => true,
            ],

            // SERVICES FISCAUX - AMÉRIQUE DU NORD
            [
                'name' => 'Taxes for Expats',
                'slug' => 'taxes-for-expats',
                'category' => 'legal',
                'url' => 'https://www.taxesforexpats.com/[AFFILIATE_ID]',
                'anchor_text' => 'Taxes for Expats - US tax filing abroad',
                'description' => 'US tax preparation for Americans living overseas.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['US'],
                'excluded_countries' => null,
                'keywords' => ['us taxes abroad', 'expat tax', 'american tax filing', 'fbar', 'fatca', 'déclaration fiscale américain'],
                'commission_type' => 'cpa',
                'commission_rate' => 50.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],
        ];
    }

    /**
     * ═══════════════════════════════════════════════════════════════════════════
     * PARTENAIRES AMÉRIQUE LATINE
     * ═══════════════════════════════════════════════════════════════════════════
     */
    private function getLatinAmericaAffiliates(): array
    {
        return [
            // BANQUES - AMÉRIQUE LATINE
            [
                'name' => 'Nubank',
                'slug' => 'nubank',
                'category' => 'bank',
                'url' => 'https://nubank.com.br/[AFFILIATE_ID]',
                'anchor_text' => 'Nubank - Digital bank Brazil',
                'description' => 'Latin America\'s largest digital bank.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['BR', 'MX', 'CO'],
                'excluded_countries' => null,
                'keywords' => ['nubank', 'brazil bank', 'banco digital', 'banque brésil', 'banco brasil'],
                'commission_type' => 'cpa',
                'commission_rate' => 10.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'Mercado Pago',
                'slug' => 'mercado-pago',
                'category' => 'transfer',
                'url' => 'https://www.mercadopago.com/[AFFILIATE_ID]',
                'anchor_text' => 'Mercado Pago - LatAm payments',
                'description' => 'Digital wallet and payments across Latin America.',
                'is_global' => false,
                'regions' => ['latin_america'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['mercado pago', 'latam payment', 'pago digital', 'billetera digital', 'carteira digital'],
                'commission_type' => 'cpa',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],

            // ASSURANCES - AMÉRIQUE LATINE
            [
                'name' => 'BUPA Mexico',
                'slug' => 'bupa-mexico',
                'category' => 'insurance',
                'url' => 'https://www.bupa.com.mx/[AFFILIATE_ID]',
                'anchor_text' => 'BUPA Mexico - Health insurance',
                'description' => 'International health insurance in Mexico.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['MX'],
                'excluded_countries' => null,
                'keywords' => ['bupa mexico', 'seguro salud mexico', 'health insurance mexico', 'assurance santé mexique'],
                'commission_type' => 'percentage',
                'commission_rate' => 6.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 60,
                'priority' => 80,
                'is_active' => true,
            ],

            // TÉLÉCOM - AMÉRIQUE LATINE
            [
                'name' => 'Claro',
                'slug' => 'claro',
                'category' => 'telecom',
                'url' => 'https://www.claro.com/[AFFILIATE_ID]',
                'anchor_text' => 'Claro - Latin America mobile',
                'description' => 'Leading mobile network across Latin America.',
                'is_global' => false,
                'regions' => ['latin_america'],
                'countries' => null,
                'excluded_countries' => null,
                'keywords' => ['claro', 'latam mobile', 'sim america latina', 'celular america latina'],
                'commission_type' => 'cpa',
                'commission_rate' => 5.00,
                'commission_currency' => 'USD',
                'cookie_duration_days' => 30,
                'priority' => 75,
                'is_active' => true,
            ],
        ];
    }

    /**
     * ═══════════════════════════════════════════════════════════════════════════
     * PARTENAIRES OCÉANIE
     * ═══════════════════════════════════════════════════════════════════════════
     */
    private function getOceaniaAffiliates(): array
    {
        return [
            // BANQUES - OCÉANIE
            [
                'name' => 'Westpac',
                'slug' => 'westpac',
                'category' => 'bank',
                'url' => 'https://www.westpac.com.au/[AFFILIATE_ID]',
                'anchor_text' => 'Westpac - Australian banking',
                'description' => 'Major Australian bank with expat services.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['AU', 'NZ'],
                'excluded_countries' => null,
                'keywords' => ['westpac', 'australian bank', 'australia banking', 'banque australie'],
                'commission_type' => 'cpl',
                'commission_rate' => 30.00,
                'commission_currency' => 'AUD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'ANZ',
                'slug' => 'anz',
                'category' => 'bank',
                'url' => 'https://www.anz.com.au/[AFFILIATE_ID]',
                'anchor_text' => 'ANZ - Australia & NZ banking',
                'description' => 'Banking across Australia, New Zealand and Asia-Pacific.',
                'is_global' => false,
                'regions' => ['oceania'],
                'countries' => ['SG', 'HK'],
                'excluded_countries' => null,
                'keywords' => ['anz', 'australia bank', 'new zealand bank', 'banque australie', 'banco australia'],
                'commission_type' => 'cpl',
                'commission_rate' => 30.00,
                'commission_currency' => 'AUD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],

            // ASSURANCES - OCÉANIE
            [
                'name' => 'Medibank',
                'slug' => 'medibank',
                'category' => 'insurance',
                'url' => 'https://www.medibank.com.au/[AFFILIATE_ID]',
                'anchor_text' => 'Medibank - Australian health insurance',
                'description' => 'Health insurance for residents and visitors in Australia.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['AU'],
                'excluded_countries' => null,
                'keywords' => ['medibank', 'australia health', 'oshc', 'ovhc', 'assurance santé australie'],
                'commission_type' => 'cpa',
                'commission_rate' => 50.00,
                'commission_currency' => 'AUD',
                'cookie_duration_days' => 60,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'Southern Cross Travel Insurance',
                'slug' => 'southern-cross',
                'category' => 'insurance',
                'url' => 'https://www.scti.co.nz/[AFFILIATE_ID]',
                'anchor_text' => 'Southern Cross - NZ travel insurance',
                'description' => 'Travel and health insurance in New Zealand.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['NZ'],
                'excluded_countries' => null,
                'keywords' => ['southern cross', 'nz insurance', 'new zealand health', 'assurance nouvelle zélande'],
                'commission_type' => 'percentage',
                'commission_rate' => 8.00,
                'commission_currency' => 'NZD',
                'cookie_duration_days' => 60,
                'priority' => 80,
                'is_active' => true,
            ],

            // TÉLÉCOM - OCÉANIE
            [
                'name' => 'Telstra',
                'slug' => 'telstra',
                'category' => 'telecom',
                'url' => 'https://www.telstra.com.au/[AFFILIATE_ID]',
                'anchor_text' => 'Telstra - Australia\'s #1 network',
                'description' => 'Best mobile coverage in Australia.',
                'is_global' => false,
                'regions' => null,
                'countries' => ['AU'],
                'excluded_countries' => null,
                'keywords' => ['telstra', 'australia sim', 'australian mobile', 'sim australie'],
                'commission_type' => 'cpa',
                'commission_rate' => 10.00,
                'commission_currency' => 'AUD',
                'cookie_duration_days' => 30,
                'priority' => 80,
                'is_active' => true,
            ],
        ];
    }
}