<?php

namespace Database\Seeders;

use App\Models\CtaTemplate;
use App\Models\Platform;
use Illuminate\Database\Seeder;

/**
 * CTA Templates Seeder - VERSION COMPLÈTE MULTILINGUE
 * 
 * 43+ CTA templates avec traductions complètes en 9 langues :
 * FR, EN, ES, DE, PT, RU, ZH, AR, HI
 * 
 * Structure :
 * - SOS-EXPAT : Urgence (4) + Recrutement pros (6) + Expat aidants (2)
 * - ULIXAI : Propositions (4) + Services catégories (11) + Services spécifiques (8) + Recrutement (2)
 */
class CtaTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $platforms = Platform::pluck('id', 'slug')->toArray();

        // ═══════════════════════════════════════════════════════════════════════════
        // SOS-EXPAT : URGENCE EXPATRIÉS - 4 variations
        // ═══════════════════════════════════════════════════════════════════════════
        $sosUrgence = [
            [
                'name' => 'Urgence Expat - V1',
                'slug' => 'sos-urgence-v1',
                'type' => 'both',
                'style' => 'urgent',
                'content_fr' => 'Besoin d\'aide urgente ? Un expert francophone vous répond en moins de 5 minutes.',
                'content_en' => 'Need urgent help? An English-speaking expert will respond in less than 5 minutes.',
                'content_es' => '¿Necesita ayuda urgente? Un experto hispanohablante le responde en menos de 5 minutos.',
                'content_de' => 'Dringende Hilfe benötigt? Ein deutschsprachiger Experte antwortet in weniger als 5 Minuten.',
                'content_pt' => 'Precisa de ajuda urgente? Um especialista lusófono responde em menos de 5 minutos.',
                'content_ru' => 'Нужна срочная помощь? Русскоязычный эксперт ответит менее чем за 5 минут.',
                'content_zh' => '需要紧急帮助？中文专家将在5分钟内回复您。',
                'content_ar' => 'هل تحتاج مساعدة عاجلة؟ خبير ناطق بالعربية سيرد عليك في أقل من 5 دقائق.',
                'content_hi' => 'तत्काल सहायता चाहिए? एक हिंदी-भाषी विशेषज्ञ 5 मिनट से कम में जवाब देगा।',
                'button_text_fr' => 'Parler à un expert maintenant',
                'button_text_en' => 'Talk to an expert now',
                'button_text_es' => 'Hablar con un experto ahora',
                'button_text_de' => 'Jetzt mit Experten sprechen',
                'button_text_pt' => 'Falar com especialista agora',
                'button_text_ru' => 'Поговорить с экспертом сейчас',
                'button_text_zh' => '立即与专家交谈',
                'button_text_ar' => 'تحدث مع خبير الآن',
                'button_text_hi' => 'अभी विशेषज्ञ से बात करें',
                'button_url' => 'https://sos-expat.com/{lang}/{country}/contact',
            ],
            [
                'name' => 'Urgence Expat - V2',
                'slug' => 'sos-urgence-v2',
                'type' => 'both',
                'style' => 'urgent',
                'content_fr' => 'Assistance immédiate par téléphone. Nos experts dans votre langue sont disponibles 24h/24.',
                'content_en' => 'Immediate phone assistance. Our experts in your language are available 24/7.',
                'content_es' => 'Asistencia telefónica inmediata. Nuestros expertos en su idioma están disponibles 24/7.',
                'content_de' => 'Sofortige telefonische Unterstützung. Unsere Experten in Ihrer Sprache sind rund um die Uhr verfügbar.',
                'content_pt' => 'Assistência telefônica imediata. Nossos especialistas no seu idioma estão disponíveis 24h.',
                'content_ru' => 'Немедленная телефонная помощь. Наши эксперты на вашем языке доступны круглосуточно.',
                'content_zh' => '即时电话援助。我们的中文专家全天候为您服务。',
                'content_ar' => 'مساعدة هاتفية فورية. خبراؤنا بلغتك متاحون على مدار الساعة.',
                'content_hi' => 'तत्काल फोन सहायता। आपकी भाषा में हमारे विशेषज्ञ 24/7 उपलब्ध हैं।',
                'button_text_fr' => 'Appeler un expert',
                'button_text_en' => 'Call an expert',
                'button_text_es' => 'Llamar a un experto',
                'button_text_de' => 'Experten anrufen',
                'button_text_pt' => 'Ligar para especialista',
                'button_text_ru' => 'Позвонить эксперту',
                'button_text_zh' => '致电专家',
                'button_text_ar' => 'اتصل بخبير',
                'button_text_hi' => 'विशेषज्ञ को कॉल करें',
                'button_url' => 'https://sos-expat.com/{lang}/{country}/call',
            ],
            [
                'name' => 'Urgence Expat - V3',
                'slug' => 'sos-urgence-v3',
                'type' => 'both',
                'style' => 'urgent',
                'content_fr' => 'Ne restez pas seul face à votre situation. Un expert vous accompagne en moins de 5 minutes.',
                'content_en' => 'Don\'t face your situation alone. An expert will assist you in less than 5 minutes.',
                'content_es' => 'No enfrente su situación solo. Un experto le asistirá en menos de 5 minutos.',
                'content_de' => 'Stehen Sie Ihrer Situation nicht allein gegenüber. Ein Experte unterstützt Sie in weniger als 5 Minuten.',
                'content_pt' => 'Não enfrente sua situação sozinho. Um especialista irá ajudá-lo em menos de 5 minutos.',
                'content_ru' => 'Не оставайтесь один на один с вашей ситуацией. Эксперт поможет вам менее чем за 5 минут.',
                'content_zh' => '不要独自面对您的情况。专家将在5分钟内为您提供帮助。',
                'content_ar' => 'لا تواجه وضعك وحدك. سيساعدك خبير في أقل من 5 دقائق.',
                'content_hi' => 'अपनी स्थिति का अकेले सामना न करें। एक विशेषज्ञ 5 मिनट से कम में आपकी सहायता करेगा।',
                'button_text_fr' => 'Obtenir de l\'aide maintenant',
                'button_text_en' => 'Get help now',
                'button_text_es' => 'Obtener ayuda ahora',
                'button_text_de' => 'Jetzt Hilfe erhalten',
                'button_text_pt' => 'Obter ajuda agora',
                'button_text_ru' => 'Получить помощь сейчас',
                'button_text_zh' => '立即获得帮助',
                'button_text_ar' => 'احصل على المساعدة الآن',
                'button_text_hi' => 'अभी मदद प्राप्त करें',
                'button_url' => 'https://sos-expat.com/{lang}/{country}/help',
            ],
            [
                'name' => 'Urgence Expat - V4',
                'slug' => 'sos-urgence-v4',
                'type' => 'both',
                'style' => 'urgent',
                'content_fr' => 'Réponse garantie en moins de 5 minutes. Des experts dans votre langue, prêts à vous aider.',
                'content_en' => 'Guaranteed response in less than 5 minutes. Experts in your language, ready to help.',
                'content_es' => 'Respuesta garantizada en menos de 5 minutos. Expertos en su idioma, listos para ayudar.',
                'content_de' => 'Garantierte Antwort in weniger als 5 Minuten. Experten in Ihrer Sprache, bereit zu helfen.',
                'content_pt' => 'Resposta garantida em menos de 5 minutos. Especialistas no seu idioma, prontos para ajudar.',
                'content_ru' => 'Гарантированный ответ менее чем за 5 минут. Эксперты на вашем языке готовы помочь.',
                'content_zh' => '保证5分钟内回复。您语言的专家随时为您服务。',
                'content_ar' => 'رد مضمون في أقل من 5 دقائق. خبراء بلغتك جاهزون للمساعدة.',
                'content_hi' => '5 मिनट से कम में गारंटीकृत प्रतिक्रिया। आपकी भाषा में विशेषज्ञ मदद के लिए तैयार।',
                'button_text_fr' => 'Contacter un expert',
                'button_text_en' => 'Contact an expert',
                'button_text_es' => 'Contactar un experto',
                'button_text_de' => 'Experten kontaktieren',
                'button_text_pt' => 'Contatar especialista',
                'button_text_ru' => 'Связаться с экспертом',
                'button_text_zh' => '联系专家',
                'button_text_ar' => 'اتصل بخبير',
                'button_text_hi' => 'विशेषज्ञ से संपर्क करें',
                'button_url' => 'https://sos-expat.com/{lang}/{country}/contact',
            ],
        ];

        // ═══════════════════════════════════════════════════════════════════════════
        // SOS-EXPAT : RECRUTEMENT PROFESSIONNELS - 6 métiers
        // ═══════════════════════════════════════════════════════════════════════════
        $sosRecrutement = [
            [
                'name' => 'Recrutement Avocat',
                'slug' => 'sos-recrutement-avocat',
                'type' => 'landing',
                'style' => 'primary',
                'content_fr' => 'Vous êtes avocat ? Rejoignez notre réseau et accompagnez des expatriés dans le monde entier.',
                'content_en' => 'Are you a lawyer? Join our network and support expats around the world.',
                'content_es' => '¿Es usted abogado? Únase a nuestra red y asista a expatriados en todo el mundo.',
                'content_de' => 'Sind Sie Anwalt? Treten Sie unserem Netzwerk bei und unterstützen Sie Expats weltweit.',
                'content_pt' => 'É advogado? Junte-se à nossa rede e apoie expatriados em todo o mundo.',
                'content_ru' => 'Вы адвокат? Присоединяйтесь к нашей сети и помогайте экспатам по всему миру.',
                'content_zh' => '您是律师吗？加入我们的网络，为全球外籍人士提供支持。',
                'content_ar' => 'هل أنت محامٍ؟ انضم إلى شبكتنا وساعد المغتربين حول العالم.',
                'content_hi' => 'क्या आप वकील हैं? हमारे नेटवर्क से जुड़ें और दुनिया भर में प्रवासियों की सहायता करें।',
                'button_text_fr' => 'Rejoindre le réseau SOS-Expat',
                'button_text_en' => 'Join the SOS-Expat network',
                'button_text_es' => 'Unirse a la red SOS-Expat',
                'button_text_de' => 'Dem SOS-Expat Netzwerk beitreten',
                'button_text_pt' => 'Juntar-se à rede SOS-Expat',
                'button_text_ru' => 'Присоединиться к сети SOS-Expat',
                'button_text_zh' => '加入SOS-Expat网络',
                'button_text_ar' => 'انضم إلى شبكة SOS-Expat',
                'button_text_hi' => 'SOS-Expat नेटवर्क से जुड़ें',
                'button_url' => 'https://sos-expat.com/{lang}/pro/avocat',
            ],
            [
                'name' => 'Recrutement Notaire',
                'slug' => 'sos-recrutement-notaire',
                'type' => 'landing',
                'style' => 'primary',
                'content_fr' => 'Vous êtes notaire ? Accompagnez des expatriés dans leurs démarches immobilières et successorales.',
                'content_en' => 'Are you a notary? Assist expats with their real estate and inheritance procedures.',
                'content_es' => '¿Es usted notario? Asista a expatriados en sus trámites inmobiliarios y sucesorios.',
                'content_de' => 'Sind Sie Notar? Unterstützen Sie Expats bei Immobilien- und Erbschaftsangelegenheiten.',
                'content_pt' => 'É notário? Acompanhe expatriados nos seus procedimentos imobiliários e de herança.',
                'content_ru' => 'Вы нотариус? Помогайте экспатам с недвижимостью и наследственными делами.',
                'content_zh' => '您是公证员吗？协助外籍人士处理房产和继承事务。',
                'content_ar' => 'هل أنت موثق؟ ساعد المغتربين في إجراءاتهم العقارية والميراثية.',
                'content_hi' => 'क्या आप नोटरी हैं? प्रवासियों की रियल एस्टेट और विरासत प्रक्रियाओं में सहायता करें।',
                'button_text_fr' => 'Devenir notaire partenaire',
                'button_text_en' => 'Become a partner notary',
                'button_text_es' => 'Convertirse en notario asociado',
                'button_text_de' => 'Partner-Notar werden',
                'button_text_pt' => 'Tornar-se notário parceiro',
                'button_text_ru' => 'Стать партнером-нотариусом',
                'button_text_zh' => '成为合作公证员',
                'button_text_ar' => 'كن موثقاً شريكاً',
                'button_text_hi' => 'पार्टनर नोटरी बनें',
                'button_url' => 'https://sos-expat.com/{lang}/pro/notaire',
            ],
            [
                'name' => 'Recrutement Expert-comptable',
                'slug' => 'sos-recrutement-comptable',
                'type' => 'landing',
                'style' => 'primary',
                'content_fr' => 'Vous êtes expert-comptable ? Aidez des expatriés à gérer leur fiscalité internationale.',
                'content_en' => 'Are you an accountant? Help expats manage their international taxation.',
                'content_es' => '¿Es usted contador? Ayude a expatriados a gestionar su fiscalidad internacional.',
                'content_de' => 'Sind Sie Steuerberater? Helfen Sie Expats bei ihrer internationalen Besteuerung.',
                'content_pt' => 'É contabilista? Ajude expatriados a gerir a sua fiscalidade internacional.',
                'content_ru' => 'Вы бухгалтер? Помогите экспатам с международным налогообложением.',
                'content_zh' => '您是会计师吗？帮助外籍人士管理国际税务。',
                'content_ar' => 'هل أنت محاسب؟ ساعد المغتربين في إدارة ضرائبهم الدولية.',
                'content_hi' => 'क्या आप एकाउंटेंट हैं? प्रवासियों को अंतर्राष्ट्रीय कराधान प्रबंधन में मदद करें।',
                'button_text_fr' => 'Devenir expert partenaire',
                'button_text_en' => 'Become a partner expert',
                'button_text_es' => 'Convertirse en experto asociado',
                'button_text_de' => 'Partner-Experte werden',
                'button_text_pt' => 'Tornar-se especialista parceiro',
                'button_text_ru' => 'Стать экспертом-партнером',
                'button_text_zh' => '成为合作专家',
                'button_text_ar' => 'كن خبيراً شريكاً',
                'button_text_hi' => 'पार्टनर विशेषज्ञ बनें',
                'button_url' => 'https://sos-expat.com/{lang}/pro/comptable',
            ],
            [
                'name' => 'Recrutement Traducteur',
                'slug' => 'sos-recrutement-traducteur',
                'type' => 'landing',
                'style' => 'primary',
                'content_fr' => 'Vous êtes traducteur assermenté ? Proposez vos services aux expatriés du monde entier.',
                'content_en' => 'Are you a certified translator? Offer your services to expats worldwide.',
                'content_es' => '¿Es usted traductor jurado? Ofrezca sus servicios a expatriados de todo el mundo.',
                'content_de' => 'Sind Sie vereidigter Übersetzer? Bieten Sie Ihre Dienste Expats weltweit an.',
                'content_pt' => 'É tradutor juramentado? Ofereça os seus serviços a expatriados em todo o mundo.',
                'content_ru' => 'Вы сертифицированный переводчик? Предлагайте услуги экспатам по всему миру.',
                'content_zh' => '您是认证翻译员吗？为全球外籍人士提供您的服务。',
                'content_ar' => 'هل أنت مترجم معتمد؟ قدم خدماتك للمغتربين حول العالم.',
                'content_hi' => 'क्या आप प्रमाणित अनुवादक हैं? दुनिया भर में प्रवासियों को अपनी सेवाएं प्रदान करें।',
                'button_text_fr' => 'Devenir traducteur partenaire',
                'button_text_en' => 'Become a partner translator',
                'button_text_es' => 'Convertirse en traductor asociado',
                'button_text_de' => 'Partner-Übersetzer werden',
                'button_text_pt' => 'Tornar-se tradutor parceiro',
                'button_text_ru' => 'Стать переводчиком-партнером',
                'button_text_zh' => '成为合作翻译员',
                'button_text_ar' => 'كن مترجماً شريكاً',
                'button_text_hi' => 'पार्टनर अनुवादक बनें',
                'button_url' => 'https://sos-expat.com/{lang}/pro/traducteur',
            ],
            [
                'name' => 'Recrutement Médecin',
                'slug' => 'sos-recrutement-medecin',
                'type' => 'landing',
                'style' => 'primary',
                'content_fr' => 'Vous êtes médecin ? Accompagnez des expatriés pour leurs consultations médicales.',
                'content_en' => 'Are you a doctor? Support expats with their medical consultations.',
                'content_es' => '¿Es usted médico? Acompañe a expatriados en sus consultas médicas.',
                'content_de' => 'Sind Sie Arzt? Begleiten Sie Expats bei ihren medizinischen Konsultationen.',
                'content_pt' => 'É médico? Acompanhe expatriados nas suas consultas médicas.',
                'content_ru' => 'Вы врач? Сопровождайте экспатов на медицинских консультациях.',
                'content_zh' => '您是医生吗？为外籍人士的医疗咨询提供支持。',
                'content_ar' => 'هل أنت طبيب؟ رافق المغتربين في استشاراتهم الطبية.',
                'content_hi' => 'क्या आप डॉक्टर हैं? प्रवासियों की चिकित्सा परामर्श में सहायता करें।',
                'button_text_fr' => 'Devenir médecin partenaire',
                'button_text_en' => 'Become a partner doctor',
                'button_text_es' => 'Convertirse en médico asociado',
                'button_text_de' => 'Partner-Arzt werden',
                'button_text_pt' => 'Tornar-se médico parceiro',
                'button_text_ru' => 'Стать врачом-партнером',
                'button_text_zh' => '成为合作医生',
                'button_text_ar' => 'كن طبيباً شريكاً',
                'button_text_hi' => 'पार्टनर डॉक्टर बनें',
                'button_url' => 'https://sos-expat.com/{lang}/pro/medecin',
            ],
            [
                'name' => 'Recrutement Psychologue',
                'slug' => 'sos-recrutement-psychologue',
                'type' => 'landing',
                'style' => 'primary',
                'content_fr' => 'Vous êtes psychologue ? Aidez des expatriés à surmonter les défis de l\'expatriation.',
                'content_en' => 'Are you a psychologist? Help expats overcome the challenges of expatriation.',
                'content_es' => '¿Es usted psicólogo? Ayude a expatriados a superar los desafíos de la expatriación.',
                'content_de' => 'Sind Sie Psychologe? Helfen Sie Expats, die Herausforderungen des Auslandslebens zu meistern.',
                'content_pt' => 'É psicólogo? Ajude expatriados a superar os desafios da expatriação.',
                'content_ru' => 'Вы психолог? Помогите экспатам преодолеть трудности эмиграции.',
                'content_zh' => '您是心理学家吗？帮助外籍人士克服海外生活的挑战。',
                'content_ar' => 'هل أنت طبيب نفسي؟ ساعد المغتربين على تجاوز تحديات الاغتراب.',
                'content_hi' => 'क्या आप मनोवैज्ञानिक हैं? प्रवासियों को प्रवास की चुनौतियों से पार पाने में मदद करें।',
                'button_text_fr' => 'Devenir psychologue partenaire',
                'button_text_en' => 'Become a partner psychologist',
                'button_text_es' => 'Convertirse en psicólogo asociado',
                'button_text_de' => 'Partner-Psychologe werden',
                'button_text_pt' => 'Tornar-se psicólogo parceiro',
                'button_text_ru' => 'Стать психологом-партнером',
                'button_text_zh' => '成为合作心理学家',
                'button_text_ar' => 'كن طبيباً نفسياً شريكاً',
                'button_text_hi' => 'पार्टनर मनोवैज्ञानिक बनें',
                'button_url' => 'https://sos-expat.com/{lang}/pro/psychologue',
            ],
        ];

        // ═══════════════════════════════════════════════════════════════════════════
        // SOS-EXPAT : EXPAT AIDANTS - 2 variations
        // ═══════════════════════════════════════════════════════════════════════════
        $sosAidants = [
            [
                'name' => 'Recrutement Expat Aidant - V1',
                'slug' => 'sos-recrutement-aidant-v1',
                'type' => 'landing',
                'style' => 'secondary',
                'content_fr' => 'Vous êtes expatrié ? Devenez expat aidant par téléphone et aidez d\'autres expatriés.',
                'content_en' => 'Are you an expat? Become a phone-based expat helper and assist other expats.',
                'content_es' => '¿Es usted expatriado? Conviértase en asistente de expatriados por teléfono.',
                'content_de' => 'Sind Sie Expat? Werden Sie telefonischer Expat-Helfer und unterstützen Sie andere Expats.',
                'content_pt' => 'É expatriado? Torne-se um ajudante de expatriados por telefone.',
                'content_ru' => 'Вы экспат? Станьте телефонным помощником и помогайте другим экспатам.',
                'content_zh' => '您是外籍人士吗？成为电话外籍帮助者，帮助其他外籍人士。',
                'content_ar' => 'هل أنت مغترب؟ كن مساعداً للمغتربين عبر الهاتف وساعد المغتربين الآخرين.',
                'content_hi' => 'क्या आप प्रवासी हैं? फोन-आधारित प्रवासी सहायक बनें और अन्य प्रवासियों की मदद करें।',
                'button_text_fr' => 'Devenir expat aidant',
                'button_text_en' => 'Become an expat helper',
                'button_text_es' => 'Convertirse en asistente expatriado',
                'button_text_de' => 'Expat-Helfer werden',
                'button_text_pt' => 'Tornar-se ajudante expatriado',
                'button_text_ru' => 'Стать помощником экспатов',
                'button_text_zh' => '成为外籍帮助者',
                'button_text_ar' => 'كن مساعداً للمغتربين',
                'button_text_hi' => 'प्रवासी सहायक बनें',
                'button_url' => 'https://sos-expat.com/{lang}/expat-aidant',
            ],
            [
                'name' => 'Recrutement Expat Aidant - V2',
                'slug' => 'sos-recrutement-aidant-v2',
                'type' => 'landing',
                'style' => 'secondary',
                'content_fr' => 'Partagez votre expérience d\'expatrié. Aidez d\'autres expatriés depuis chez vous, par téléphone.',
                'content_en' => 'Share your expat experience. Help other expats from home, by phone.',
                'content_es' => 'Comparta su experiencia de expatriado. Ayude a otros expatriados desde casa, por teléfono.',
                'content_de' => 'Teilen Sie Ihre Expat-Erfahrung. Helfen Sie anderen Expats von zu Hause aus per Telefon.',
                'content_pt' => 'Partilhe a sua experiência de expatriado. Ajude outros expatriados a partir de casa, por telefone.',
                'content_ru' => 'Поделитесь своим опытом экспата. Помогайте другим экспатам из дома по телефону.',
                'content_zh' => '分享您的外籍经验。在家通过电话帮助其他外籍人士。',
                'content_ar' => 'شارك تجربتك كمغترب. ساعد المغتربين الآخرين من المنزل عبر الهاتف.',
                'content_hi' => 'अपने प्रवासी अनुभव को साझा करें। घर से फोन द्वारा अन्य प्रवासियों की मदद करें।',
                'button_text_fr' => 'Rejoindre les expat aidants',
                'button_text_en' => 'Join expat helpers',
                'button_text_es' => 'Unirse a los asistentes expatriados',
                'button_text_de' => 'Den Expat-Helfern beitreten',
                'button_text_pt' => 'Juntar-se aos ajudantes expatriados',
                'button_text_ru' => 'Присоединиться к помощникам экспатов',
                'button_text_zh' => '加入外籍帮助者',
                'button_text_ar' => 'انضم إلى مساعدي المغتربين',
                'button_text_hi' => 'प्रवासी सहायकों से जुड़ें',
                'button_url' => 'https://sos-expat.com/{lang}/expat-aidant/inscription',
            ],
        ];

        // ═══════════════════════════════════════════════════════════════════════════
        // ULIXAI : DEMANDE PROPOSITIONS - 4 variations
        // ═══════════════════════════════════════════════════════════════════════════
        $ulixaiPropositions = [
            [
                'name' => 'Demande Propositions - V1',
                'slug' => 'ulixai-propositions-v1',
                'type' => 'both',
                'style' => 'primary',
                'content_fr' => 'Recevez des propositions de tarifs et choisissez le prestataire en fonction de son offre, avis et compétences.',
                'content_en' => 'Receive pricing proposals and choose the provider based on their offer, reviews and skills.',
                'content_es' => 'Reciba propuestas de tarifas y elija al proveedor según su oferta, opiniones y competencias.',
                'content_de' => 'Erhalten Sie Preisvorschläge und wählen Sie den Anbieter nach Angebot, Bewertungen und Kompetenzen.',
                'content_pt' => 'Receba propostas de preços e escolha o prestador com base na oferta, avaliações e competências.',
                'content_ru' => 'Получите ценовые предложения и выберите специалиста по его предложению, отзывам и компетенциям.',
                'content_zh' => '接收报价并根据服务商的报价、评价和能力进行选择。',
                'content_ar' => 'احصل على عروض أسعار واختر مقدم الخدمة بناءً على عرضه وتقييماته وكفاءاته.',
                'content_hi' => 'मूल्य प्रस्ताव प्राप्त करें और प्रदाता को उनके प्रस्ताव, समीक्षाओं और कौशल के आधार पर चुनें।',
                'button_text_fr' => 'Recevoir des propositions',
                'button_text_en' => 'Receive proposals',
                'button_text_es' => 'Recibir propuestas',
                'button_text_de' => 'Angebote erhalten',
                'button_text_pt' => 'Receber propostas',
                'button_text_ru' => 'Получить предложения',
                'button_text_zh' => '获取报价',
                'button_text_ar' => 'احصل على عروض',
                'button_text_hi' => 'प्रस्ताव प्राप्त करें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/{service}/demande',
            ],
            [
                'name' => 'Demande Propositions - V2',
                'slug' => 'ulixai-propositions-v2',
                'type' => 'both',
                'style' => 'primary',
                'content_fr' => 'Recevez des propositions de tarifs directement en ligne. Comparez et choisissez en toute confiance.',
                'content_en' => 'Receive pricing proposals directly online. Compare and choose with confidence.',
                'content_es' => 'Reciba propuestas de tarifas directamente en línea. Compare y elija con confianza.',
                'content_de' => 'Erhalten Sie Preisvorschläge direkt online. Vergleichen und wählen Sie mit Vertrauen.',
                'content_pt' => 'Receba propostas de preços diretamente online. Compare e escolha com confiança.',
                'content_ru' => 'Получите ценовые предложения прямо онлайн. Сравнивайте и выбирайте с уверенностью.',
                'content_zh' => '直接在线接收报价。自信地比较和选择。',
                'content_ar' => 'احصل على عروض أسعار مباشرة عبر الإنترنت. قارن واختر بثقة.',
                'content_hi' => 'सीधे ऑनलाइन मूल्य प्रस्ताव प्राप्त करें। आत्मविश्वास से तुलना करें और चुनें।',
                'button_text_fr' => 'Demander des propositions',
                'button_text_en' => 'Request proposals',
                'button_text_es' => 'Solicitar propuestas',
                'button_text_de' => 'Angebote anfordern',
                'button_text_pt' => 'Solicitar propostas',
                'button_text_ru' => 'Запросить предложения',
                'button_text_zh' => '请求报价',
                'button_text_ar' => 'اطلب عروضاً',
                'button_text_hi' => 'प्रस्ताव का अनुरोध करें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/{service}/demande',
            ],
            [
                'name' => 'Demande Propositions - V3',
                'slug' => 'ulixai-propositions-v3',
                'type' => 'both',
                'style' => 'primary',
                'content_fr' => 'Décrivez votre besoin, recevez jusqu\'à 5 propositions de prestataires vérifiés.',
                'content_en' => 'Describe your need, receive up to 5 proposals from verified providers.',
                'content_es' => 'Describa su necesidad, reciba hasta 5 propuestas de proveedores verificados.',
                'content_de' => 'Beschreiben Sie Ihren Bedarf, erhalten Sie bis zu 5 Angebote von verifizierten Anbietern.',
                'content_pt' => 'Descreva sua necessidade, receba até 5 propostas de prestadores verificados.',
                'content_ru' => 'Опишите вашу потребность, получите до 5 предложений от проверенных специалистов.',
                'content_zh' => '描述您的需求，从经过验证的服务商那里获得多达5个报价。',
                'content_ar' => 'صف حاجتك، واحصل على ما يصل إلى 5 عروض من مقدمي خدمات موثوقين.',
                'content_hi' => 'अपनी आवश्यकता का वर्णन करें, सत्यापित प्रदाताओं से 5 प्रस्ताव तक प्राप्त करें।',
                'button_text_fr' => 'Obtenir des propositions gratuites',
                'button_text_en' => 'Get free proposals',
                'button_text_es' => 'Obtener propuestas gratuitas',
                'button_text_de' => 'Kostenlose Angebote erhalten',
                'button_text_pt' => 'Obter propostas gratuitas',
                'button_text_ru' => 'Получить бесплатные предложения',
                'button_text_zh' => '获取免费报价',
                'button_text_ar' => 'احصل على عروض مجانية',
                'button_text_hi' => 'मुफ्त प्रस्ताव प्राप्त करें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/{service}/demande',
            ],
            [
                'name' => 'Demande Propositions - V4',
                'slug' => 'ulixai-propositions-v4',
                'type' => 'both',
                'style' => 'primary',
                'content_fr' => 'C\'est gratuit et sans engagement. Recevez des propositions de prestataires qualifiés près de chez vous.',
                'content_en' => 'It\'s free and no obligation. Receive proposals from qualified providers near you.',
                'content_es' => 'Es gratis y sin compromiso. Reciba propuestas de proveedores calificados cerca de usted.',
                'content_de' => 'Es ist kostenlos und unverbindlich. Erhalten Sie Angebote von qualifizierten Anbietern in Ihrer Nähe.',
                'content_pt' => 'É gratuito e sem compromisso. Receba propostas de prestadores qualificados perto de você.',
                'content_ru' => 'Это бесплатно и без обязательств. Получите предложения от квалифицированных специалистов рядом с вами.',
                'content_zh' => '免费且无需承诺。从您附近的合格服务商那里获得报价。',
                'content_ar' => 'مجاني وبدون التزام. احصل على عروض من مقدمي خدمات مؤهلين بالقرب منك.',
                'content_hi' => 'यह मुफ़्त है और कोई बाध्यता नहीं। अपने पास योग्य प्रदाताओं से प्रस्ताव प्राप्त करें।',
                'button_text_fr' => 'Trouver un prestataire',
                'button_text_en' => 'Find a provider',
                'button_text_es' => 'Encontrar un proveedor',
                'button_text_de' => 'Anbieter finden',
                'button_text_pt' => 'Encontrar um prestador',
                'button_text_ru' => 'Найти специалиста',
                'button_text_zh' => '寻找服务商',
                'button_text_ar' => 'ابحث عن مقدم خدمة',
                'button_text_hi' => 'प्रदाता खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/{service}/demande',
            ],
        ];

        // ═══════════════════════════════════════════════════════════════════════════
        // ULIXAI : 11 CATÉGORIES DE SERVICES (avec traductions complètes)
        // ═══════════════════════════════════════════════════════════════════════════
        $ulixaiServices = [
            // 1. Administratif, Immigration & Visas
            [
                'name' => 'Service Immigration Visas',
                'slug' => 'ulixai-service-immigration',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Visa, permis de séjour ou démarches administratives ? Trouvez un expert pour vous accompagner.',
                'content_en' => 'Visa, residence permit or administrative procedures? Find an expert to assist you.',
                'content_es' => '¿Visa, permiso de residencia o trámites administrativos? Encuentre un experto que le asista.',
                'content_de' => 'Visum, Aufenthaltserlaubnis oder Verwaltungsverfahren? Finden Sie einen Experten, der Sie begleitet.',
                'content_pt' => 'Visto, autorização de residência ou procedimentos administrativos? Encontre um especialista para o acompanhar.',
                'content_ru' => 'Виза, вид на жительство или административные процедуры? Найдите эксперта для сопровождения.',
                'content_zh' => '签证、居留许可或行政手续？找到专家为您提供帮助。',
                'content_ar' => 'تأشيرة أو إقامة أو إجراءات إدارية؟ ابحث عن خبير لمساعدتك.',
                'content_hi' => 'वीज़ा, निवास परमिट या प्रशासनिक प्रक्रियाएं? आपकी सहायता के लिए एक विशेषज्ञ खोजें।',
                'button_text_fr' => 'Trouver un expert immigration',
                'button_text_en' => 'Find an immigration expert',
                'button_text_es' => 'Encontrar un experto en inmigración',
                'button_text_de' => 'Einwanderungsexperten finden',
                'button_text_pt' => 'Encontrar especialista em imigração',
                'button_text_ru' => 'Найти эксперта по иммиграции',
                'button_text_zh' => '寻找移民专家',
                'button_text_ar' => 'ابحث عن خبير هجرة',
                'button_text_hi' => 'आप्रवासन विशेषज्ञ खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/immigration/demande',
            ],
            // 2. Logement & Installation
            [
                'name' => 'Service Logement Installation',
                'slug' => 'ulixai-service-logement',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Recherche de logement ou installation ? Trouvez des agents immobiliers spécialisés expatriés.',
                'content_en' => 'Looking for housing or settling in? Find real estate agents specialized in expats.',
                'content_es' => '¿Buscando vivienda o instalándose? Encuentre agentes inmobiliarios especializados en expatriados.',
                'content_de' => 'Wohnungssuche oder Einrichtung? Finden Sie auf Expats spezialisierte Immobilienmakler.',
                'content_pt' => 'Procurando moradia ou se instalando? Encontre agentes imobiliários especializados em expatriados.',
                'content_ru' => 'Ищете жилье или обустраиваетесь? Найдите агентов по недвижимости, специализирующихся на экспатах.',
                'content_zh' => '寻找住房或安顿？找到专门为外籍人士服务的房地产经纪人。',
                'content_ar' => 'تبحث عن سكن أو استقرار؟ ابحث عن وكلاء عقارات متخصصين في المغتربين.',
                'content_hi' => 'आवास या बसावट की तलाश में? प्रवासियों में विशेषज्ञ रियल एस्टेट एजेंट खोजें।',
                'button_text_fr' => 'Trouver un agent immobilier',
                'button_text_en' => 'Find a real estate agent',
                'button_text_es' => 'Encontrar un agente inmobiliario',
                'button_text_de' => 'Immobilienmakler finden',
                'button_text_pt' => 'Encontrar agente imobiliário',
                'button_text_ru' => 'Найти агента по недвижимости',
                'button_text_zh' => '寻找房产经纪人',
                'button_text_ar' => 'ابحث عن وكيل عقارات',
                'button_text_hi' => 'रियल एस्टेट एजेंट खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/logement/demande',
            ],
            // 3. Vie Pratique
            [
                'name' => 'Service Vie Pratique',
                'slug' => 'ulixai-service-vie-pratique',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Aide à domicile, ménage, informatique ou garde d\'animaux ? Trouvez des prestataires de confiance.',
                'content_en' => 'Home help, cleaning, IT or pet care? Find trusted providers.',
                'content_es' => '¿Ayuda doméstica, limpieza, informática o cuidado de mascotas? Encuentre proveedores de confianza.',
                'content_de' => 'Haushaltshilfe, Reinigung, IT oder Tierpflege? Finden Sie vertrauenswürdige Anbieter.',
                'content_pt' => 'Ajuda doméstica, limpeza, informática ou cuidado de animais? Encontre prestadores de confiança.',
                'content_ru' => 'Домашняя помощь, уборка, IT или уход за животными? Найдите надежных специалистов.',
                'content_zh' => '家政服务、清洁、IT或宠物护理？找到值得信赖的服务商。',
                'content_ar' => 'مساعدة منزلية أو تنظيف أو تقنية معلومات أو رعاية حيوانات؟ ابحث عن مقدمي خدمات موثوقين.',
                'content_hi' => 'घरेलू सहायता, सफाई, IT या पालतू देखभाल? विश्वसनीय प्रदाता खोजें।',
                'button_text_fr' => 'Trouver un prestataire',
                'button_text_en' => 'Find a provider',
                'button_text_es' => 'Encontrar un proveedor',
                'button_text_de' => 'Anbieter finden',
                'button_text_pt' => 'Encontrar prestador',
                'button_text_ru' => 'Найти специалиста',
                'button_text_zh' => '寻找服务商',
                'button_text_ar' => 'ابحث عن مقدم خدمة',
                'button_text_hi' => 'प्रदाता खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/vie-pratique/demande',
            ],
            // 4. Traducteurs & Interprètes
            [
                'name' => 'Service Traduction',
                'slug' => 'ulixai-service-traduction',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Besoin d\'une traduction ou d\'un interprète ? Trouvez des traducteurs assermentés et interprètes qualifiés.',
                'content_en' => 'Need a translation or interpreter? Find certified translators and qualified interpreters.',
                'content_es' => '¿Necesita una traducción o intérprete? Encuentre traductores jurados e intérpretes cualificados.',
                'content_de' => 'Brauchen Sie eine Übersetzung oder einen Dolmetscher? Finden Sie vereidigte Übersetzer und qualifizierte Dolmetscher.',
                'content_pt' => 'Precisa de tradução ou intérprete? Encontre tradutores juramentados e intérpretes qualificados.',
                'content_ru' => 'Нужен перевод или переводчик? Найдите сертифицированных переводчиков и квалифицированных устных переводчиков.',
                'content_zh' => '需要翻译或口译？找到认证翻译员和合格口译员。',
                'content_ar' => 'هل تحتاج ترجمة أو مترجم فوري؟ ابحث عن مترجمين معتمدين ومترجمين فوريين مؤهلين.',
                'content_hi' => 'अनुवाद या दुभाषिया चाहिए? प्रमाणित अनुवादक और योग्य दुभाषिए खोजें।',
                'button_text_fr' => 'Trouver un traducteur',
                'button_text_en' => 'Find a translator',
                'button_text_es' => 'Encontrar un traductor',
                'button_text_de' => 'Übersetzer finden',
                'button_text_pt' => 'Encontrar tradutor',
                'button_text_ru' => 'Найти переводчика',
                'button_text_zh' => '寻找翻译员',
                'button_text_ar' => 'ابحث عن مترجم',
                'button_text_hi' => 'अनुवादक खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/traduction/demande',
            ],
            // 5. Banques, Fiscalité & Assurances
            [
                'name' => 'Service Banque Fiscalité',
                'slug' => 'ulixai-service-banque-fiscalite',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Compte bancaire, fiscalité ou assurance ? Trouvez des experts financiers spécialisés expatriés.',
                'content_en' => 'Bank account, taxes or insurance? Find financial experts specialized in expats.',
                'content_es' => '¿Cuenta bancaria, impuestos o seguros? Encuentre expertos financieros especializados en expatriados.',
                'content_de' => 'Bankkonto, Steuern oder Versicherung? Finden Sie auf Expats spezialisierte Finanzexperten.',
                'content_pt' => 'Conta bancária, impostos ou seguro? Encontre especialistas financeiros especializados em expatriados.',
                'content_ru' => 'Банковский счет, налоги или страховка? Найдите финансовых экспертов, специализирующихся на экспатах.',
                'content_zh' => '银行账户、税务或保险？找到专门为外籍人士服务的金融专家。',
                'content_ar' => 'حساب بنكي أو ضرائب أو تأمين؟ ابحث عن خبراء ماليين متخصصين في المغتربين.',
                'content_hi' => 'बैंक खाता, कर या बीमा? प्रवासियों में विशेषज्ञ वित्तीय विशेषज्ञ खोजें।',
                'button_text_fr' => 'Trouver un expert financier',
                'button_text_en' => 'Find a financial expert',
                'button_text_es' => 'Encontrar un experto financiero',
                'button_text_de' => 'Finanzexperten finden',
                'button_text_pt' => 'Encontrar especialista financeiro',
                'button_text_ru' => 'Найти финансового эксперта',
                'button_text_zh' => '寻找金融专家',
                'button_text_ar' => 'ابحث عن خبير مالي',
                'button_text_hi' => 'वित्तीय विशेषज्ञ खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/banque-fiscalite/demande',
            ],
            // 6. Permis de Conduire, Mobilité & Transport
            [
                'name' => 'Service Mobilité Transport',
                'slug' => 'ulixai-service-mobilite',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Permis de conduire, immatriculation ou transport ? Trouvez des prestataires pour vos démarches mobilité.',
                'content_en' => 'Driver\'s license, registration or transport? Find providers for your mobility needs.',
                'content_es' => '¿Licencia de conducir, matriculación o transporte? Encuentre proveedores para sus necesidades de movilidad.',
                'content_de' => 'Führerschein, Zulassung oder Transport? Finden Sie Anbieter für Ihre Mobilitätsbedürfnisse.',
                'content_pt' => 'Carta de condução, matrícula ou transporte? Encontre prestadores para as suas necessidades de mobilidade.',
                'content_ru' => 'Водительские права, регистрация или транспорт? Найдите специалистов для ваших потребностей в мобильности.',
                'content_zh' => '驾照、注册或交通？找到满足您出行需求的服务商。',
                'content_ar' => 'رخصة قيادة أو تسجيل أو نقل؟ ابحث عن مقدمي خدمات لاحتياجات التنقل الخاصة بك.',
                'content_hi' => 'ड्राइविंग लाइसेंस, पंजीकरण या परिवहन? अपनी गतिशीलता आवश्यकताओं के लिए प्रदाता खोजें।',
                'button_text_fr' => 'Trouver un prestataire mobilité',
                'button_text_en' => 'Find a mobility provider',
                'button_text_es' => 'Encontrar un proveedor de movilidad',
                'button_text_de' => 'Mobilitätsanbieter finden',
                'button_text_pt' => 'Encontrar prestador de mobilidade',
                'button_text_ru' => 'Найти специалиста по мобильности',
                'button_text_zh' => '寻找出行服务商',
                'button_text_ar' => 'ابحث عن مقدم خدمات التنقل',
                'button_text_hi' => 'गतिशीलता प्रदाता खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/mobilite/demande',
            ],
            // 7. Famille, Éducation & Langues
            [
                'name' => 'Service Famille Éducation',
                'slug' => 'ulixai-service-famille-education',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'École, cours de langue ou garde d\'enfants ? Trouvez des prestataires pour votre famille.',
                'content_en' => 'School, language courses or childcare? Find providers for your family.',
                'content_es' => '¿Escuela, cursos de idiomas o cuidado de niños? Encuentre proveedores para su familia.',
                'content_de' => 'Schule, Sprachkurse oder Kinderbetreuung? Finden Sie Anbieter für Ihre Familie.',
                'content_pt' => 'Escola, cursos de idiomas ou cuidado infantil? Encontre prestadores para a sua família.',
                'content_ru' => 'Школа, языковые курсы или уход за детьми? Найдите специалистов для вашей семьи.',
                'content_zh' => '学校、语言课程或儿童看护？为您的家庭找到服务商。',
                'content_ar' => 'مدرسة أو دورات لغة أو رعاية أطفال؟ ابحث عن مقدمي خدمات لعائلتك.',
                'content_hi' => 'स्कूल, भाषा पाठ्यक्रम या चाइल्डकेयर? अपने परिवार के लिए प्रदाता खोजें।',
                'button_text_fr' => 'Trouver un prestataire famille',
                'button_text_en' => 'Find a family provider',
                'button_text_es' => 'Encontrar un proveedor familiar',
                'button_text_de' => 'Familienanbieter finden',
                'button_text_pt' => 'Encontrar prestador familiar',
                'button_text_ru' => 'Найти семейного специалиста',
                'button_text_zh' => '寻找家庭服务商',
                'button_text_ar' => 'ابحث عن مقدم خدمات عائلية',
                'button_text_hi' => 'परिवार प्रदाता खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/famille-education/demande',
            ],
            // 8. Déménagement & Logistique
            [
                'name' => 'Service Déménagement',
                'slug' => 'ulixai-service-demenagement',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Déménagement international ou stockage ? Trouvez des déménageurs et logisticiens professionnels.',
                'content_en' => 'International move or storage? Find professional movers and logistics providers.',
                'content_es' => '¿Mudanza internacional o almacenamiento? Encuentre mudanzas y logística profesional.',
                'content_de' => 'Internationaler Umzug oder Lagerung? Finden Sie professionelle Umzugsunternehmen und Logistikanbieter.',
                'content_pt' => 'Mudança internacional ou armazenamento? Encontre empresas de mudanças e logística profissionais.',
                'content_ru' => 'Международный переезд или хранение? Найдите профессиональных перевозчиков и логистов.',
                'content_zh' => '国际搬家或仓储？找到专业的搬家公司和物流服务商。',
                'content_ar' => 'انتقال دولي أو تخزين؟ ابحث عن شركات نقل ولوجستيات محترفة.',
                'content_hi' => 'अंतर्राष्ट्रीय स्थानांतरण या भंडारण? पेशेवर मूवर्स और लॉजिस्टिक्स प्रदाता खोजें।',
                'button_text_fr' => 'Trouver un déménageur',
                'button_text_en' => 'Find a mover',
                'button_text_es' => 'Encontrar una empresa de mudanzas',
                'button_text_de' => 'Umzugsunternehmen finden',
                'button_text_pt' => 'Encontrar empresa de mudanças',
                'button_text_ru' => 'Найти перевозчика',
                'button_text_zh' => '寻找搬家公司',
                'button_text_ar' => 'ابحث عن شركة نقل',
                'button_text_hi' => 'मूवर खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/demenagement/demande',
            ],
            // 9. Emploi & Développement Professionnel
            [
                'name' => 'Service Emploi Carrière',
                'slug' => 'ulixai-service-emploi',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Recherche d\'emploi, CV ou coaching ? Trouvez des experts pour booster votre carrière à l\'étranger.',
                'content_en' => 'Job search, CV or coaching? Find experts to boost your career abroad.',
                'content_es' => '¿Búsqueda de empleo, CV o coaching? Encuentre expertos para impulsar su carrera en el extranjero.',
                'content_de' => 'Jobsuche, Lebenslauf oder Coaching? Finden Sie Experten, um Ihre Karriere im Ausland zu fördern.',
                'content_pt' => 'Procura de emprego, CV ou coaching? Encontre especialistas para impulsionar a sua carreira no exterior.',
                'content_ru' => 'Поиск работы, резюме или коучинг? Найдите экспертов для развития карьеры за рубежом.',
                'content_zh' => '找工作、简历或职业指导？找到专家助力您的海外职业发展。',
                'content_ar' => 'بحث عن عمل أو سيرة ذاتية أو تدريب؟ ابحث عن خبراء لتعزيز مسيرتك المهنية في الخارج.',
                'content_hi' => 'नौकरी खोज, CV या कोचिंग? विदेश में अपने करियर को बढ़ावा देने के लिए विशेषज्ञ खोजें।',
                'button_text_fr' => 'Trouver un expert carrière',
                'button_text_en' => 'Find a career expert',
                'button_text_es' => 'Encontrar un experto en carrera',
                'button_text_de' => 'Karriereexperten finden',
                'button_text_pt' => 'Encontrar especialista em carreira',
                'button_text_ru' => 'Найти карьерного эксперта',
                'button_text_zh' => '寻找职业专家',
                'button_text_ar' => 'ابحث عن خبير وظيفي',
                'button_text_hi' => 'करियर विशेषज्ञ खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/emploi/demande',
            ],
            // 10. Entreprise & Business
            [
                'name' => 'Service Entreprise Business',
                'slug' => 'ulixai-service-business',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Création d\'entreprise ou développement commercial ? Trouvez des experts pour votre business à l\'étranger.',
                'content_en' => 'Company creation or business development? Find experts for your business abroad.',
                'content_es' => '¿Creación de empresa o desarrollo comercial? Encuentre expertos para su negocio en el extranjero.',
                'content_de' => 'Firmengründung oder Geschäftsentwicklung? Finden Sie Experten für Ihr Unternehmen im Ausland.',
                'content_pt' => 'Criação de empresa ou desenvolvimento comercial? Encontre especialistas para o seu negócio no exterior.',
                'content_ru' => 'Создание компании или развитие бизнеса? Найдите экспертов для вашего бизнеса за рубежом.',
                'content_zh' => '创业或业务发展？为您的海外业务找到专家。',
                'content_ar' => 'إنشاء شركة أو تطوير أعمال؟ ابحث عن خبراء لعملك في الخارج.',
                'content_hi' => 'कंपनी निर्माण या व्यवसाय विकास? अपने विदेशी व्यापार के लिए विशेषज्ञ खोजें।',
                'button_text_fr' => 'Trouver un expert business',
                'button_text_en' => 'Find a business expert',
                'button_text_es' => 'Encontrar un experto en negocios',
                'button_text_de' => 'Business-Experten finden',
                'button_text_pt' => 'Encontrar especialista em negócios',
                'button_text_ru' => 'Найти бизнес-эксперта',
                'button_text_zh' => '寻找商业专家',
                'button_text_ar' => 'ابحث عن خبير أعمال',
                'button_text_hi' => 'बिजनेस विशेषज्ञ खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/business/demande',
            ],
            // 11. Santé & Bien-être
            [
                'name' => 'Service Santé Bien-être',
                'slug' => 'ulixai-service-sante',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Assurance santé, médecin ou accompagnement médical ? Trouvez des prestataires santé pour expatriés.',
                'content_en' => 'Health insurance, doctor or medical support? Find healthcare providers for expats.',
                'content_es' => '¿Seguro de salud, médico o acompañamiento médico? Encuentre proveedores de salud para expatriados.',
                'content_de' => 'Krankenversicherung, Arzt oder medizinische Begleitung? Finden Sie Gesundheitsanbieter für Expats.',
                'content_pt' => 'Seguro de saúde, médico ou acompanhamento médico? Encontre prestadores de saúde para expatriados.',
                'content_ru' => 'Медицинская страховка, врач или медицинская поддержка? Найдите медицинских специалистов для экспатов.',
                'content_zh' => '健康保险、医生或医疗支持？找到为外籍人士服务的医疗保健提供商。',
                'content_ar' => 'تأمين صحي أو طبيب أو دعم طبي؟ ابحث عن مقدمي رعاية صحية للمغتربين.',
                'content_hi' => 'स्वास्थ्य बीमा, डॉक्टर या चिकित्सा सहायता? प्रवासियों के लिए स्वास्थ्य सेवा प्रदाता खोजें।',
                'button_text_fr' => 'Trouver un prestataire santé',
                'button_text_en' => 'Find a healthcare provider',
                'button_text_es' => 'Encontrar un proveedor de salud',
                'button_text_de' => 'Gesundheitsanbieter finden',
                'button_text_pt' => 'Encontrar prestador de saúde',
                'button_text_ru' => 'Найти медицинского специалиста',
                'button_text_zh' => '寻找医疗服务商',
                'button_text_ar' => 'ابحث عن مقدم رعاية صحية',
                'button_text_hi' => 'स्वास्थ्य सेवा प्रदाता खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/sante/demande',
            ],
        ];

        // ═══════════════════════════════════════════════════════════════════════════
        // ULIXAI : SERVICES SPÉCIFIQUES POPULAIRES - 8 services
        // ═══════════════════════════════════════════════════════════════════════════
        $ulixaiSpecifiques = [
            // Assurance santé internationale
            [
                'name' => 'Service Assurance Santé',
                'slug' => 'ulixai-specific-assurance-sante',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Assurance santé internationale ? Comparez les offres des assureurs spécialisés expatriés.',
                'content_en' => 'International health insurance? Compare offers from expat-specialized insurers.',
                'content_es' => '¿Seguro de salud internacional? Compare ofertas de aseguradoras especializadas en expatriados.',
                'content_de' => 'Internationale Krankenversicherung? Vergleichen Sie Angebote von auf Expats spezialisierten Versicherern.',
                'content_pt' => 'Seguro de saúde internacional? Compare ofertas de seguradoras especializadas em expatriados.',
                'content_ru' => 'Международная медицинская страховка? Сравните предложения страховщиков, специализирующихся на экспатах.',
                'content_zh' => '国际健康保险？比较专门为外籍人士服务的保险公司的报价。',
                'content_ar' => 'تأمين صحي دولي؟ قارن عروض شركات التأمين المتخصصة في المغتربين.',
                'content_hi' => 'अंतर्राष्ट्रीय स्वास्थ्य बीमा? प्रवासी-विशेषज्ञ बीमाकर्ताओं के प्रस्तावों की तुलना करें।',
                'button_text_fr' => 'Comparer les assurances santé',
                'button_text_en' => 'Compare health insurance',
                'button_text_es' => 'Comparar seguros de salud',
                'button_text_de' => 'Krankenversicherungen vergleichen',
                'button_text_pt' => 'Comparar seguros de saúde',
                'button_text_ru' => 'Сравнить медицинские страховки',
                'button_text_zh' => '比较健康保险',
                'button_text_ar' => 'قارن التأمين الصحي',
                'button_text_hi' => 'स्वास्थ्य बीमा की तुलना करें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/assurance-sante/demande',
            ],
            // Cours de langue
            [
                'name' => 'Service Cours Langue',
                'slug' => 'ulixai-specific-cours-langue',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Apprendre la langue locale ? Trouvez des professeurs et écoles de langue qualifiés.',
                'content_en' => 'Learn the local language? Find qualified language teachers and schools.',
                'content_es' => '¿Aprender el idioma local? Encuentre profesores y escuelas de idiomas cualificados.',
                'content_de' => 'Die Landessprache lernen? Finden Sie qualifizierte Sprachlehrer und Schulen.',
                'content_pt' => 'Aprender o idioma local? Encontre professores e escolas de idiomas qualificados.',
                'content_ru' => 'Изучить местный язык? Найдите квалифицированных преподавателей и языковые школы.',
                'content_zh' => '学习当地语言？找到合格的语言教师和学校。',
                'content_ar' => 'تعلم اللغة المحلية؟ ابحث عن مدرسين ومدارس لغات مؤهلين.',
                'content_hi' => 'स्थानीय भाषा सीखें? योग्य भाषा शिक्षक और स्कूल खोजें।',
                'button_text_fr' => 'Trouver un cours de langue',
                'button_text_en' => 'Find a language course',
                'button_text_es' => 'Encontrar un curso de idiomas',
                'button_text_de' => 'Sprachkurs finden',
                'button_text_pt' => 'Encontrar curso de idiomas',
                'button_text_ru' => 'Найти языковой курс',
                'button_text_zh' => '寻找语言课程',
                'button_text_ar' => 'ابحث عن دورة لغة',
                'button_text_hi' => 'भाषा कोर्स खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/cours-langue/demande',
            ],
            // École internationale
            [
                'name' => 'Service École Internationale',
                'slug' => 'ulixai-specific-ecole-internationale',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Scolarité de vos enfants ? Découvrez les écoles internationales adaptées à vos besoins.',
                'content_en' => 'Your children\'s schooling? Discover international schools suited to your needs.',
                'content_es' => '¿Escolaridad de sus hijos? Descubra escuelas internacionales adaptadas a sus necesidades.',
                'content_de' => 'Schulbildung Ihrer Kinder? Entdecken Sie internationale Schulen, die Ihren Bedürfnissen entsprechen.',
                'content_pt' => 'Escolaridade dos seus filhos? Descubra escolas internacionais adaptadas às suas necessidades.',
                'content_ru' => 'Образование ваших детей? Откройте международные школы, подходящие вашим потребностям.',
                'content_zh' => '您孩子的教育？发现适合您需求的国际学校。',
                'content_ar' => 'تعليم أطفالك؟ اكتشف المدارس الدولية المناسبة لاحتياجاتك.',
                'content_hi' => 'आपके बच्चों की शिक्षा? अपनी आवश्यकताओं के अनुरूप अंतर्राष्ट्रीय स्कूल खोजें।',
                'button_text_fr' => 'Trouver une école internationale',
                'button_text_en' => 'Find an international school',
                'button_text_es' => 'Encontrar una escuela internacional',
                'button_text_de' => 'Internationale Schule finden',
                'button_text_pt' => 'Encontrar escola internacional',
                'button_text_ru' => 'Найти международную школу',
                'button_text_zh' => '寻找国际学校',
                'button_text_ar' => 'ابحث عن مدرسة دولية',
                'button_text_hi' => 'अंतर्राष्ट्रीय स्कूल खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/ecole-internationale/demande',
            ],
            // Garde d'enfants
            [
                'name' => 'Service Garde Enfants',
                'slug' => 'ulixai-specific-garde-enfants',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Besoin d\'une nounou ou baby-sitter ? Trouvez des prestataires de garde d\'enfants vérifiés.',
                'content_en' => 'Need a nanny or babysitter? Find verified childcare providers.',
                'content_es' => '¿Necesita una niñera? Encuentre proveedores de cuidado infantil verificados.',
                'content_de' => 'Brauchen Sie ein Kindermädchen oder Babysitter? Finden Sie verifizierte Kinderbetreuungsanbieter.',
                'content_pt' => 'Precisa de uma babá? Encontre prestadores de cuidado infantil verificados.',
                'content_ru' => 'Нужна няня? Найдите проверенных специалистов по уходу за детьми.',
                'content_zh' => '需要保姆？找到经过验证的儿童看护提供商。',
                'content_ar' => 'هل تحتاج مربية؟ ابحث عن مقدمي رعاية أطفال موثوقين.',
                'content_hi' => 'नैनी या बेबीसिटर चाहिए? सत्यापित चाइल्डकेयर प्रदाता खोजें।',
                'button_text_fr' => 'Trouver une garde d\'enfants',
                'button_text_en' => 'Find childcare',
                'button_text_es' => 'Encontrar cuidado infantil',
                'button_text_de' => 'Kinderbetreuung finden',
                'button_text_pt' => 'Encontrar cuidado infantil',
                'button_text_ru' => 'Найти няню',
                'button_text_zh' => '寻找儿童看护',
                'button_text_ar' => 'ابحث عن رعاية أطفال',
                'button_text_hi' => 'चाइल्डकेयर खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/garde-enfants/demande',
            ],
            // Compte bancaire
            [
                'name' => 'Service Compte Bancaire',
                'slug' => 'ulixai-specific-compte-bancaire',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Ouvrir un compte bancaire à l\'étranger ? Trouvez des conseillers bancaires pour expatriés.',
                'content_en' => 'Open a bank account abroad? Find banking advisors for expats.',
                'content_es' => '¿Abrir una cuenta bancaria en el extranjero? Encuentre asesores bancarios para expatriados.',
                'content_de' => 'Ein Bankkonto im Ausland eröffnen? Finden Sie Bankberater für Expats.',
                'content_pt' => 'Abrir conta bancária no exterior? Encontre consultores bancários para expatriados.',
                'content_ru' => 'Открыть банковский счет за границей? Найдите банковских консультантов для экспатов.',
                'content_zh' => '在国外开设银行账户？找到为外籍人士服务的银行顾问。',
                'content_ar' => 'فتح حساب بنكي في الخارج؟ ابحث عن مستشارين مصرفيين للمغتربين.',
                'content_hi' => 'विदेश में बैंक खाता खोलें? प्रवासियों के लिए बैंकिंग सलाहकार खोजें।',
                'button_text_fr' => 'Trouver un conseiller bancaire',
                'button_text_en' => 'Find a banking advisor',
                'button_text_es' => 'Encontrar un asesor bancario',
                'button_text_de' => 'Bankberater finden',
                'button_text_pt' => 'Encontrar consultor bancário',
                'button_text_ru' => 'Найти банковского консультанта',
                'button_text_zh' => '寻找银行顾问',
                'button_text_ar' => 'ابحث عن مستشار مصرفي',
                'button_text_hi' => 'बैंकिंग सलाहकार खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/compte-bancaire/demande',
            ],
            // Expert visa
            [
                'name' => 'Service Expert Visa',
                'slug' => 'ulixai-specific-visa',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Visa ou permis de séjour ? Trouvez des experts en immigration pour vous accompagner.',
                'content_en' => 'Visa or residence permit? Find immigration experts to assist you.',
                'content_es' => '¿Visa o permiso de residencia? Encuentre expertos en inmigración para asistirle.',
                'content_de' => 'Visum oder Aufenthaltserlaubnis? Finden Sie Einwanderungsexperten, die Sie begleiten.',
                'content_pt' => 'Visto ou autorização de residência? Encontre especialistas em imigração para o acompanhar.',
                'content_ru' => 'Виза или вид на жительство? Найдите экспертов по иммиграции для сопровождения.',
                'content_zh' => '签证或居留许可？找到移民专家为您提供帮助。',
                'content_ar' => 'تأشيرة أو إقامة؟ ابحث عن خبراء هجرة لمساعدتك.',
                'content_hi' => 'वीज़ा या निवास परमिट? आपकी सहायता के लिए आप्रवासन विशेषज्ञ खोजें।',
                'button_text_fr' => 'Trouver un expert visa',
                'button_text_en' => 'Find a visa expert',
                'button_text_es' => 'Encontrar un experto en visas',
                'button_text_de' => 'Visumexperten finden',
                'button_text_pt' => 'Encontrar especialista em vistos',
                'button_text_ru' => 'Найти эксперта по визам',
                'button_text_zh' => '寻找签证专家',
                'button_text_ar' => 'ابحث عن خبير تأشيرات',
                'button_text_hi' => 'वीज़ा विशेषज्ञ खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/visa/demande',
            ],
            // Expert fiscal
            [
                'name' => 'Service Expert Fiscal',
                'slug' => 'ulixai-specific-fiscalite',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Fiscalité internationale ? Trouvez des experts-comptables spécialisés expatriés.',
                'content_en' => 'International taxes? Find expat-specialized accountants.',
                'content_es' => '¿Fiscalidad internacional? Encuentre contadores especializados en expatriados.',
                'content_de' => 'Internationale Besteuerung? Finden Sie auf Expats spezialisierte Steuerberater.',
                'content_pt' => 'Fiscalidade internacional? Encontre contabilistas especializados em expatriados.',
                'content_ru' => 'Международное налогообложение? Найдите бухгалтеров, специализирующихся на экспатах.',
                'content_zh' => '国际税务？找到专门为外籍人士服务的会计师。',
                'content_ar' => 'ضرائب دولية؟ ابحث عن محاسبين متخصصين في المغتربين.',
                'content_hi' => 'अंतर्राष्ट्रीय कर? प्रवासी-विशेषज्ञ एकाउंटेंट खोजें।',
                'button_text_fr' => 'Trouver un expert fiscal',
                'button_text_en' => 'Find a tax expert',
                'button_text_es' => 'Encontrar un experto fiscal',
                'button_text_de' => 'Steuerexperten finden',
                'button_text_pt' => 'Encontrar especialista fiscal',
                'button_text_ru' => 'Найти налогового эксперта',
                'button_text_zh' => '寻找税务专家',
                'button_text_ar' => 'ابحث عن خبير ضرائب',
                'button_text_hi' => 'कर विशेषज्ञ खोजें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/fiscalite/demande',
            ],
            // Déménagement international
            [
                'name' => 'Service Déménagement International',
                'slug' => 'ulixai-specific-demenagement-international',
                'type' => 'article',
                'style' => 'primary',
                'content_fr' => 'Déménagement international ? Recevez des propositions de déménageurs professionnels vérifiés.',
                'content_en' => 'International move? Receive proposals from verified professional movers.',
                'content_es' => '¿Mudanza internacional? Reciba propuestas de empresas de mudanzas profesionales verificadas.',
                'content_de' => 'Internationaler Umzug? Erhalten Sie Angebote von verifizierten professionellen Umzugsunternehmen.',
                'content_pt' => 'Mudança internacional? Receba propostas de empresas de mudanças profissionais verificadas.',
                'content_ru' => 'Международный переезд? Получите предложения от проверенных профессиональных перевозчиков.',
                'content_zh' => '国际搬家？从经过验证的专业搬家公司那里获得报价。',
                'content_ar' => 'انتقال دولي؟ احصل على عروض من شركات نقل محترفة موثوقة.',
                'content_hi' => 'अंतर्राष्ट्रीय स्थानांतरण? सत्यापित पेशेवर मूवर्स से प्रस्ताव प्राप्त करें।',
                'button_text_fr' => 'Comparer les déménageurs',
                'button_text_en' => 'Compare movers',
                'button_text_es' => 'Comparar empresas de mudanzas',
                'button_text_de' => 'Umzugsunternehmen vergleichen',
                'button_text_pt' => 'Comparar empresas de mudanças',
                'button_text_ru' => 'Сравнить перевозчиков',
                'button_text_zh' => '比较搬家公司',
                'button_text_ar' => 'قارن شركات النقل',
                'button_text_hi' => 'मूवर्स की तुलना करें',
                'button_url' => 'https://ulixai.com/{lang}/{country}/demenagement-international/demande',
            ],
        ];

        // ═══════════════════════════════════════════════════════════════════════════
        // ULIXAI : RECRUTEMENT PRESTATAIRES - 2 variations
        // ═══════════════════════════════════════════════════════════════════════════
        $ulixaiRecrutement = [
            [
                'name' => 'Recrutement Prestataire - V1',
                'slug' => 'ulixai-recrutement-v1',
                'type' => 'landing',
                'style' => 'secondary',
                'content_fr' => 'Vous êtes prestataire de services ? Rejoignez Ulixai et développez votre clientèle d\'expatriés.',
                'content_en' => 'Are you a service provider? Join Ulixai and grow your expat clientele.',
                'content_es' => '¿Es usted proveedor de servicios? Únase a Ulixai y desarrolle su clientela de expatriados.',
                'content_de' => 'Sind Sie Dienstleister? Treten Sie Ulixai bei und erweitern Sie Ihre Expat-Kundschaft.',
                'content_pt' => 'É prestador de serviços? Junte-se à Ulixai e desenvolva sua clientela de expatriados.',
                'content_ru' => 'Вы поставщик услуг? Присоединяйтесь к Ulixai и расширяйте клиентуру экспатов.',
                'content_zh' => '您是服务提供商吗？加入Ulixai，发展您的外籍客户群。',
                'content_ar' => 'هل أنت مقدم خدمات؟ انضم إلى Ulixai ووسع قاعدة عملائك من المغتربين.',
                'content_hi' => 'क्या आप सेवा प्रदाता हैं? Ulixai से जुड़ें और अपने प्रवासी ग्राहकों को बढ़ाएं।',
                'button_text_fr' => 'Devenir prestataire Ulixai',
                'button_text_en' => 'Become an Ulixai provider',
                'button_text_es' => 'Convertirse en proveedor Ulixai',
                'button_text_de' => 'Ulixai-Anbieter werden',
                'button_text_pt' => 'Tornar-se prestador Ulixai',
                'button_text_ru' => 'Стать партнером Ulixai',
                'button_text_zh' => '成为Ulixai服务商',
                'button_text_ar' => 'كن مقدم خدمة Ulixai',
                'button_text_hi' => 'Ulixai प्रदाता बनें',
                'button_url' => 'https://ulixai.com/{lang}/pro/inscription',
            ],
            [
                'name' => 'Recrutement Prestataire - V2',
                'slug' => 'ulixai-recrutement-v2',
                'type' => 'landing',
                'style' => 'secondary',
                'content_fr' => 'Prestataires : accédez à des milliers d\'expatriés qui recherchent vos services.',
                'content_en' => 'Providers: access thousands of expats looking for your services.',
                'content_es' => 'Proveedores: acceda a miles de expatriados que buscan sus servicios.',
                'content_de' => 'Anbieter: Erreichen Sie Tausende von Expats, die Ihre Dienste suchen.',
                'content_pt' => 'Prestadores: aceda a milhares de expatriados que procuram os seus serviços.',
                'content_ru' => 'Поставщики: получите доступ к тысячам экспатов, ищущих ваши услуги.',
                'content_zh' => '服务商：接触成千上万寻找您服务的外籍人士。',
                'content_ar' => 'مقدمو الخدمات: تواصل مع آلاف المغتربين الذين يبحثون عن خدماتكم.',
                'content_hi' => 'प्रदाता: हजारों प्रवासियों तक पहुंचें जो आपकी सेवाओं की तलाश में हैं।',
                'button_text_fr' => 'Rejoindre Ulixai',
                'button_text_en' => 'Join Ulixai',
                'button_text_es' => 'Unirse a Ulixai',
                'button_text_de' => 'Ulixai beitreten',
                'button_text_pt' => 'Juntar-se à Ulixai',
                'button_text_ru' => 'Присоединиться к Ulixai',
                'button_text_zh' => '加入Ulixai',
                'button_text_ar' => 'انضم إلى Ulixai',
                'button_text_hi' => 'Ulixai से जुड़ें',
                'button_url' => 'https://ulixai.com/{lang}/pro/inscription',
            ],
        ];

        // ═══════════════════════════════════════════════════════════════════════════
        // INSERTION EN BASE DE DONNÉES
        // ═══════════════════════════════════════════════════════════════════════════
        
        // SOS-Expat CTAs
        foreach ($sosUrgence as $cta) {
            if (isset($platforms['sos-expat'])) {
                $cta['platform_id'] = $platforms['sos-expat'];
                $cta['is_active'] = true;
                CtaTemplate::create($cta);
            }
        }
        
        foreach ($sosRecrutement as $cta) {
            if (isset($platforms['sos-expat'])) {
                $cta['platform_id'] = $platforms['sos-expat'];
                $cta['is_active'] = true;
                CtaTemplate::create($cta);
            }
        }
        
        foreach ($sosAidants as $cta) {
            if (isset($platforms['sos-expat'])) {
                $cta['platform_id'] = $platforms['sos-expat'];
                $cta['is_active'] = true;
                CtaTemplate::create($cta);
            }
        }
        
        // Ulixai CTAs
        foreach ($ulixaiPropositions as $cta) {
            if (isset($platforms['ulixai'])) {
                $cta['platform_id'] = $platforms['ulixai'];
                $cta['is_active'] = true;
                CtaTemplate::create($cta);
            }
        }
        
        foreach ($ulixaiServices as $cta) {
            if (isset($platforms['ulixai'])) {
                $cta['platform_id'] = $platforms['ulixai'];
                $cta['is_active'] = true;
                CtaTemplate::create($cta);
            }
        }
        
        foreach ($ulixaiSpecifiques as $cta) {
            if (isset($platforms['ulixai'])) {
                $cta['platform_id'] = $platforms['ulixai'];
                $cta['is_active'] = true;
                CtaTemplate::create($cta);
            }
        }
        
        foreach ($ulixaiRecrutement as $cta) {
            if (isset($platforms['ulixai'])) {
                $cta['platform_id'] = $platforms['ulixai'];
                $cta['is_active'] = true;
                CtaTemplate::create($cta);
            }
        }
        
        // Compter le total
        $total = count($sosUrgence) + count($sosRecrutement) + count($sosAidants) 
               + count($ulixaiPropositions) + count($ulixaiServices) 
               + count($ulixaiSpecifiques) + count($ulixaiRecrutement);
        
        $this->command->info("   ✅ {$total} CTA templates créés avec traductions complètes en 9 langues");
    }
}